export default {

  LOAD_AVAILABLE_ITEMS: 'LOAD_AVAILABLE_ITEMS',
  ADD_ITEM_TO_SHOPCART: 'ADD_ITEM_TO_SHOPCART',
  DELETE_ITEM_FROM_SHOPCART: 'DELETE_ITEM_FROM_SHOPCART',
  INCREASE_ITEM_STOCK: 'INCREASE_ITEM_STOCK',
  CALCULATE_TOTAL_PRICE: 'CALCULATE_TOTAL_PRICE',
  DELETE_ALL_CART_ITEMS: 'DELETE_ALL_CART_ITEMS'

};
