const actionTypes = {
  LOAD_FIRST_TIME: 'LOAD_FIRST_TIME',
  DELETE_TAG_ARTIST: 'DELETE_TAG_ARTIST',
  DELETE_TAG_TRACK: 'DELETE_TAG_TRACK',
  ADD_TAG_ARTIST: 'ADD_TAG_ARTIST',
  ADD_TAG_TRACK: 'ADD_TAG_TRACK',
  ADD_TO_FAVOURITES: 'ADD_TO_FAVOURITES',
  GET_TRACKS: 'GET TRACKS',
  UPDATE_ALBUM_DETAIL: 'UPDATE_ALBUM_DETAIL',
  SEARCH_RECOMMENDATIONS: 'SEARCH_RECOMMENDATIONS',
  GET_BACK: 'GET_BACK',
  RETRIEVE_USER_DATA: 'RETRIEVE_USER_DATA',
  DELETE_FAVOURITE: 'DELETE_FAVOURITE'

};

export default actionTypes;
