import React from 'react';
import { unmountComponentAtNode, render } from 'react-dom';
import { act } from 'react-dom/test-utils';
import { BrowserRouter } from 'react-router-dom';
import Recommendations from './recommendations';
import loadFirstTime from '../../flux/actions/actions';
import dispatcher from '../../flux/dispatcher/dispatcher';
import actionTypes from '../../flux/actions/actionTypes';

const mockData = [
  {
    album_type: 'album',
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/5LnlX7FdPg0ocmyBzOzDQW'
        },
        href: 'https://api.spotify.com/v1/artists/5LnlX7FdPg0ocmyBzOzDQW',
        id: '5LnlX7FdPg0ocmyBzOzDQW',
        name: 'JUDAH.',
        type: 'artist',
        uri: 'spotify:artist:5LnlX7FdPg0ocmyBzOzDQW'
      }
    ],
    available_markets: [
      'AD',
      'AE',
      'AL',
      'AR',
      'AT',
      'AU',
      'BA',
      'BE',
      'BG',
      'BH',
      'BO',
      'BR',
      'BY',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'GT',
      'HK',
      'HN',
      'HR',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IS',
      'IT',
      'JO',
      'JP',
      'KR',
      'KW',
      'KZ',
      'LB',
      'LI',
      'LT',
      'LU',
      'LV',
      'MA',
      'MC',
      'MD',
      'ME',
      'MK',
      'MT',
      'MX',
      'MY',
      'NI',
      'NL',
      'NO',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PH',
      'PL',
      'PS',
      'PT',
      'PY',
      'QA',
      'RO',
      'RS',
      'RU',
      'SA',
      'SE',
      'SG',
      'SI',
      'SK',
      'SV',
      'TH',
      'TN',
      'TR',
      'TW',
      'UA',
      'US',
      'UY',
      'VN',
      'XK',
      'ZA'
    ],
    external_urls: {
      spotify: 'https://open.spotify.com/album/2g1SAILgSY5GB70zgYarni'
    },
    href: 'https://api.spotify.com/v1/albums/2g1SAILgSY5GB70zgYarni',
    id: '2g1SAILgSY5GB70zgYarni',
    images: [
      {
        height: 640,
        url: 'https://i.scdn.co/image/ab67616d0000b273f0e2e741a731b917de2263cd',
        width: 640
      },
      {
        height: 300,
        url: 'https://i.scdn.co/image/ab67616d00001e02f0e2e741a731b917de2263cd',
        width: 300
      },
      {
        height: 64,
        url: 'https://i.scdn.co/image/ab67616d00004851f0e2e741a731b917de2263cd',
        width: 64
      }
    ],
    name: '7',
    release_date: '2021-02-05',
    release_date_precision: 'day',
    total_tracks: 7,
    type: 'album',
    uri: 'spotify:album:2g1SAILgSY5GB70zgYarni'
  },
  {
    album_type: 'album',
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/5G49Sq5mMzAkGL4ZP6eVPY'
        },
        href: 'https://api.spotify.com/v1/artists/5G49Sq5mMzAkGL4ZP6eVPY',
        id: '5G49Sq5mMzAkGL4ZP6eVPY',
        name: 'The Staves',
        type: 'artist',
        uri: 'spotify:artist:5G49Sq5mMzAkGL4ZP6eVPY'
      }
    ],
    available_markets: [
      'AD',
      'AE',
      'AL',
      'AR',
      'AT',
      'AU',
      'BA',
      'BE',
      'BG',
      'BH',
      'BO',
      'BR',
      'BY',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'GT',
      'HK',
      'HN',
      'HR',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IS',
      'IT',
      'JO',
      'JP',
      'KR',
      'KW',
      'KZ',
      'LB',
      'LI',
      'LT',
      'LU',
      'LV',
      'MA',
      'MC',
      'MD',
      'ME',
      'MK',
      'MT',
      'MX',
      'MY',
      'NI',
      'NL',
      'NO',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PH',
      'PL',
      'PS',
      'PT',
      'PY',
      'QA',
      'RO',
      'RS',
      'RU',
      'SA',
      'SE',
      'SG',
      'SI',
      'SK',
      'SV',
      'TH',
      'TN',
      'TR',
      'TW',
      'UA',
      'US',
      'UY',
      'VN',
      'XK',
      'ZA'
    ],
    external_urls: {
      spotify: 'https://open.spotify.com/album/66A7X1EqFQEEvuE5Nezqrl'
    },
    href: 'https://api.spotify.com/v1/albums/66A7X1EqFQEEvuE5Nezqrl',
    id: '66A7X1EqFQEEvuE5Nezqrl',
    images: [
      {
        height: 640,
        url: 'https://i.scdn.co/image/ab67616d0000b273bc68a2dab1d410206172f45c',
        width: 640
      },
      {
        height: 300,
        url: 'https://i.scdn.co/image/ab67616d00001e02bc68a2dab1d410206172f45c',
        width: 300
      },
      {
        height: 64,
        url: 'https://i.scdn.co/image/ab67616d00004851bc68a2dab1d410206172f45c',
        width: 64
      }
    ],
    name: 'Good Woman',
    release_date: '2021-02-05',
    release_date_precision: 'day',
    total_tracks: 12,
    type: 'album',
    uri: 'spotify:album:66A7X1EqFQEEvuE5Nezqrl'
  },
  {
    album_type: 'single',
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/1URwpSLjCBhRjnw4SUwNyL'
        },
        href: 'https://api.spotify.com/v1/artists/1URwpSLjCBhRjnw4SUwNyL',
        id: '1URwpSLjCBhRjnw4SUwNyL',
        name: 'Bobby Sessions',
        type: 'artist',
        uri: 'spotify:artist:1URwpSLjCBhRjnw4SUwNyL'
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/181bsRPaVXVlUKXrxwZfHK'
        },
        href: 'https://api.spotify.com/v1/artists/181bsRPaVXVlUKXrxwZfHK',
        id: '181bsRPaVXVlUKXrxwZfHK',
        name: 'Megan Thee Stallion',
        type: 'artist',
        uri: 'spotify:artist:181bsRPaVXVlUKXrxwZfHK'
      }
    ],
    available_markets: [
      'AD',
      'AE',
      'AL',
      'AR',
      'AT',
      'AU',
      'BA',
      'BE',
      'BG',
      'BH',
      'BO',
      'BR',
      'BY',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'GT',
      'HK',
      'HN',
      'HR',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IS',
      'IT',
      'JO',
      'JP',
      'KR',
      'KW',
      'KZ',
      'LB',
      'LI',
      'LT',
      'LU',
      'LV',
      'MA',
      'MC',
      'MD',
      'ME',
      'MK',
      'MT',
      'MX',
      'MY',
      'NI',
      'NL',
      'NO',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PH',
      'PL',
      'PS',
      'PT',
      'PY',
      'QA',
      'RO',
      'RS',
      'RU',
      'SA',
      'SE',
      'SG',
      'SI',
      'SK',
      'SV',
      'TH',
      'TN',
      'TR',
      'TW',
      'UA',
      'US',
      'UY',
      'VN',
      'XK',
      'ZA'
    ],
    external_urls: {
      spotify: 'https://open.spotify.com/album/73W1nB0OXc4YnawDDyW48D'
    },
    href: 'https://api.spotify.com/v1/albums/73W1nB0OXc4YnawDDyW48D',
    id: '73W1nB0OXc4YnawDDyW48D',
    images: [
      {
        height: 640,
        url: 'https://i.scdn.co/image/ab67616d0000b27365d78395ac75ef72d865ffa7',
        width: 640
      },
      {
        height: 300,
        url: 'https://i.scdn.co/image/ab67616d00001e0265d78395ac75ef72d865ffa7',
        width: 300
      },
      {
        height: 64,
        url: 'https://i.scdn.co/image/ab67616d0000485165d78395ac75ef72d865ffa7',
        width: 64
      }
    ],
    name: "I'm A King (From The Amazon Original Motion Picture Soundtrack Coming 2 America)",
    release_date: '2021-02-05',
    release_date_precision: 'day',
    total_tracks: 1,
    type: 'album',
    uri: 'spotify:album:73W1nB0OXc4YnawDDyW48D'
  },
  {
    album_type: 'single',
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/4aKdmOXdUKX07HVd3sGgzw'
        },
        href: 'https://api.spotify.com/v1/artists/4aKdmOXdUKX07HVd3sGgzw',
        id: '4aKdmOXdUKX07HVd3sGgzw',
        name: 'Rezz',
        type: 'artist',
        uri: 'spotify:artist:4aKdmOXdUKX07HVd3sGgzw'
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/6oFs3qk4VepIVFdoD4jmsy'
        },
        href: 'https://api.spotify.com/v1/artists/6oFs3qk4VepIVFdoD4jmsy',
        id: '6oFs3qk4VepIVFdoD4jmsy',
        name: 'PVRIS',
        type: 'artist',
        uri: 'spotify:artist:6oFs3qk4VepIVFdoD4jmsy'
      }
    ],
    available_markets: [
      'AD',
      'AE',
      'AL',
      'AR',
      'AT',
      'AU',
      'BA',
      'BE',
      'BG',
      'BH',
      'BO',
      'BR',
      'BY',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'GT',
      'HK',
      'HN',
      'HR',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IS',
      'IT',
      'JO',
      'JP',
      'KR',
      'KW',
      'KZ',
      'LB',
      'LI',
      'LT',
      'LU',
      'LV',
      'MA',
      'MC',
      'MD',
      'ME',
      'MK',
      'MT',
      'MX',
      'MY',
      'NI',
      'NL',
      'NO',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PH',
      'PL',
      'PS',
      'PT',
      'PY',
      'QA',
      'RO',
      'RS',
      'RU',
      'SA',
      'SE',
      'SG',
      'SI',
      'SK',
      'SV',
      'TH',
      'TN',
      'TR',
      'TW',
      'UA',
      'US',
      'UY',
      'VN',
      'XK',
      'ZA'
    ],
    external_urls: {
      spotify: 'https://open.spotify.com/album/66jlZyvN4g2VBo9RNDYrOS'
    },
    href: 'https://api.spotify.com/v1/albums/66jlZyvN4g2VBo9RNDYrOS',
    id: '66jlZyvN4g2VBo9RNDYrOS',
    images: [
      {
        height: 640,
        url: 'https://i.scdn.co/image/ab67616d0000b273849406b4fcdf688bcca8e4c2',
        width: 640
      },
      {
        height: 300,
        url: 'https://i.scdn.co/image/ab67616d00001e02849406b4fcdf688bcca8e4c2',
        width: 300
      },
      {
        height: 64,
        url: 'https://i.scdn.co/image/ab67616d00004851849406b4fcdf688bcca8e4c2',
        width: 64
      }
    ],
    name: 'Sacrificial (feat. PVRIS)',
    release_date: '2021-02-05',
    release_date_precision: 'day',
    total_tracks: 1,
    type: 'album',
    uri: 'spotify:album:66jlZyvN4g2VBo9RNDYrOS'
  },
  {
    album_type: 'album',
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/5rXanKVc707nhQmW1Is2pB'
        },
        href: 'https://api.spotify.com/v1/artists/5rXanKVc707nhQmW1Is2pB',
        id: '5rXanKVc707nhQmW1Is2pB',
        name: 'Jimi Somewhere',
        type: 'artist',
        uri: 'spotify:artist:5rXanKVc707nhQmW1Is2pB'
      }
    ],
    available_markets: [
      'AD',
      'AE',
      'AL',
      'AR',
      'AT',
      'AU',
      'BA',
      'BE',
      'BG',
      'BH',
      'BO',
      'BR',
      'BY',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'GT',
      'HK',
      'HN',
      'HR',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IS',
      'IT',
      'JO',
      'JP',
      'KR',
      'KW',
      'KZ',
      'LB',
      'LI',
      'LT',
      'LU',
      'LV',
      'MA',
      'MC',
      'MD',
      'ME',
      'MK',
      'MT',
      'MX',
      'MY',
      'NI',
      'NL',
      'NO',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PH',
      'PL',
      'PS',
      'PT',
      'PY',
      'QA',
      'RO',
      'RS',
      'RU',
      'SA',
      'SE',
      'SG',
      'SI',
      'SK',
      'SV',
      'TH',
      'TN',
      'TR',
      'TW',
      'UA',
      'US',
      'UY',
      'VN',
      'XK',
      'ZA'
    ],
    external_urls: {
      spotify: 'https://open.spotify.com/album/4bdojHk9PdqHImi61mEaHJ'
    },
    href: 'https://api.spotify.com/v1/albums/4bdojHk9PdqHImi61mEaHJ',
    id: '4bdojHk9PdqHImi61mEaHJ',
    images: [
      {
        height: 640,
        url: 'https://i.scdn.co/image/ab67616d0000b273277fa0bf5196bb99e83ebae5',
        width: 640
      },
      {
        height: 300,
        url: 'https://i.scdn.co/image/ab67616d00001e02277fa0bf5196bb99e83ebae5',
        width: 300
      },
      {
        height: 64,
        url: 'https://i.scdn.co/image/ab67616d00004851277fa0bf5196bb99e83ebae5',
        width: 64
      }
    ],
    name: 'Nothing Gold Can Stay',
    release_date: '2021-02-05',
    release_date_precision: 'day',
    total_tracks: 12,
    type: 'album',
    uri: 'spotify:album:4bdojHk9PdqHImi61mEaHJ'
  },
  {
    album_type: 'album',
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/4PztbfCny3X9gBjlpgvjYo'
        },
        href: 'https://api.spotify.com/v1/artists/4PztbfCny3X9gBjlpgvjYo',
        id: '4PztbfCny3X9gBjlpgvjYo',
        name: 'Aaron Lee Tasjan',
        type: 'artist',
        uri: 'spotify:artist:4PztbfCny3X9gBjlpgvjYo'
      }
    ],
    available_markets: [
      'AD',
      'AE',
      'AL',
      'AR',
      'AT',
      'AU',
      'BA',
      'BE',
      'BG',
      'BH',
      'BO',
      'BR',
      'BY',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'GT',
      'HK',
      'HN',
      'HR',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IS',
      'IT',
      'JO',
      'JP',
      'KR',
      'KW',
      'KZ',
      'LB',
      'LI',
      'LT',
      'LU',
      'LV',
      'MA',
      'MC',
      'MD',
      'ME',
      'MK',
      'MT',
      'MX',
      'MY',
      'NI',
      'NL',
      'NO',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PH',
      'PL',
      'PS',
      'PT',
      'PY',
      'QA',
      'RO',
      'RS',
      'RU',
      'SA',
      'SE',
      'SG',
      'SI',
      'SK',
      'SV',
      'TH',
      'TN',
      'TR',
      'TW',
      'UA',
      'US',
      'UY',
      'VN',
      'XK',
      'ZA'
    ],
    external_urls: {
      spotify: 'https://open.spotify.com/album/28OiUhh3Dl2HtgPOF5BFPg'
    },
    href: 'https://api.spotify.com/v1/albums/28OiUhh3Dl2HtgPOF5BFPg',
    id: '28OiUhh3Dl2HtgPOF5BFPg',
    images: [
      {
        height: 640,
        url: 'https://i.scdn.co/image/ab67616d0000b273def408e94e79b1b0beb5581a',
        width: 640
      },
      {
        height: 300,
        url: 'https://i.scdn.co/image/ab67616d00001e02def408e94e79b1b0beb5581a',
        width: 300
      },
      {
        height: 64,
        url: 'https://i.scdn.co/image/ab67616d00004851def408e94e79b1b0beb5581a',
        width: 64
      }
    ],
    name: 'Tasjan! Tasjan! Tasjan!',
    release_date: '2021-02-05',
    release_date_precision: 'day',
    total_tracks: 11,
    type: 'album',
    uri: 'spotify:album:28OiUhh3Dl2HtgPOF5BFPg'
  },
  {
    album_type: 'single',
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/49jTY62Cpw3RYo4dLuG43W'
        },
        href: 'https://api.spotify.com/v1/artists/49jTY62Cpw3RYo4dLuG43W',
        id: '49jTY62Cpw3RYo4dLuG43W',
        name: 'Cian Ducrot',
        type: 'artist',
        uri: 'spotify:artist:49jTY62Cpw3RYo4dLuG43W'
      }
    ],
    available_markets: [
      'AD',
      'AE',
      'AL',
      'AR',
      'AT',
      'AU',
      'BA',
      'BE',
      'BG',
      'BH',
      'BO',
      'BR',
      'BY',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'GT',
      'HK',
      'HN',
      'HR',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IS',
      'IT',
      'JO',
      'JP',
      'KR',
      'KW',
      'KZ',
      'LB',
      'LI',
      'LT',
      'LU',
      'LV',
      'MA',
      'MC',
      'MD',
      'ME',
      'MK',
      'MT',
      'MX',
      'MY',
      'NI',
      'NL',
      'NO',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PH',
      'PL',
      'PS',
      'PT',
      'PY',
      'QA',
      'RO',
      'RS',
      'RU',
      'SA',
      'SE',
      'SG',
      'SI',
      'SK',
      'SV',
      'TH',
      'TN',
      'TR',
      'TW',
      'UA',
      'US',
      'UY',
      'VN',
      'XK',
      'ZA'
    ],
    external_urls: {
      spotify: 'https://open.spotify.com/album/0LEquNgl5YmOrDs2yLymJV'
    },
    href: 'https://api.spotify.com/v1/albums/0LEquNgl5YmOrDs2yLymJV',
    id: '0LEquNgl5YmOrDs2yLymJV',
    images: [
      {
        height: 640,
        url: 'https://i.scdn.co/image/ab67616d0000b273c306a29d9c4ff7da8746ec3d',
        width: 640
      },
      {
        height: 300,
        url: 'https://i.scdn.co/image/ab67616d00001e02c306a29d9c4ff7da8746ec3d',
        width: 300
      },
      {
        height: 64,
        url: 'https://i.scdn.co/image/ab67616d00004851c306a29d9c4ff7da8746ec3d',
        width: 64
      }
    ],
    name: 'Not Usually Like This',
    release_date: '2021-02-04',
    release_date_precision: 'day',
    total_tracks: 1,
    type: 'album',
    uri: 'spotify:album:0LEquNgl5YmOrDs2yLymJV'
  },
  {
    album_type: 'single',
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/2GH8Mzo3Ur1AdOnGUUpt17'
        },
        href: 'https://api.spotify.com/v1/artists/2GH8Mzo3Ur1AdOnGUUpt17',
        id: '2GH8Mzo3Ur1AdOnGUUpt17',
        name: 'Octo Octa',
        type: 'artist',
        uri: 'spotify:artist:2GH8Mzo3Ur1AdOnGUUpt17'
      }
    ],
    available_markets: [
      'AD',
      'AE',
      'AL',
      'AR',
      'AT',
      'AU',
      'BA',
      'BE',
      'BG',
      'BH',
      'BO',
      'BR',
      'BY',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'GT',
      'HK',
      'HN',
      'HR',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IS',
      'IT',
      'JO',
      'JP',
      'KR',
      'KW',
      'KZ',
      'LB',
      'LI',
      'LT',
      'LU',
      'LV',
      'MA',
      'MC',
      'MD',
      'ME',
      'MK',
      'MT',
      'MX',
      'MY',
      'NI',
      'NL',
      'NO',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PH',
      'PL',
      'PS',
      'PT',
      'PY',
      'QA',
      'RO',
      'RS',
      'RU',
      'SA',
      'SE',
      'SG',
      'SI',
      'SK',
      'SV',
      'TH',
      'TN',
      'TR',
      'TW',
      'UA',
      'US',
      'UY',
      'VN',
      'XK',
      'ZA'
    ],
    external_urls: {
      spotify: 'https://open.spotify.com/album/4QIzvwiurfYaLWAATLXU0N'
    },
    href: 'https://api.spotify.com/v1/albums/4QIzvwiurfYaLWAATLXU0N',
    id: '4QIzvwiurfYaLWAATLXU0N',
    images: [
      {
        height: 640,
        url: 'https://i.scdn.co/image/ab67616d0000b2731f908fe6b87a142d5aaaaffa',
        width: 640
      },
      {
        height: 300,
        url: 'https://i.scdn.co/image/ab67616d00001e021f908fe6b87a142d5aaaaffa',
        width: 300
      },
      {
        height: 64,
        url: 'https://i.scdn.co/image/ab67616d000048511f908fe6b87a142d5aaaaffa',
        width: 64
      }
    ],
    name: "She's Calling EP",
    release_date: '2021-02-05',
    release_date_precision: 'day',
    total_tracks: 3,
    type: 'album',
    uri: 'spotify:album:4QIzvwiurfYaLWAATLXU0N'
  },
  {
    album_type: 'single',
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/1iEaqWaYpKo9x0OrEq7Q7z'
        },
        href: 'https://api.spotify.com/v1/artists/1iEaqWaYpKo9x0OrEq7Q7z',
        id: '1iEaqWaYpKo9x0OrEq7Q7z',
        name: 'Ayron Jones',
        type: 'artist',
        uri: 'spotify:artist:1iEaqWaYpKo9x0OrEq7Q7z'
      }
    ],
    available_markets: [
      'AD',
      'AE',
      'AL',
      'AR',
      'AT',
      'AU',
      'BA',
      'BE',
      'BG',
      'BH',
      'BO',
      'BR',
      'BY',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'GT',
      'HK',
      'HN',
      'HR',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IS',
      'IT',
      'JO',
      'JP',
      'KR',
      'KW',
      'KZ',
      'LB',
      'LI',
      'LT',
      'LU',
      'LV',
      'MA',
      'MC',
      'MD',
      'ME',
      'MK',
      'MT',
      'MX',
      'MY',
      'NI',
      'NL',
      'NO',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PH',
      'PL',
      'PS',
      'PT',
      'PY',
      'QA',
      'RO',
      'RS',
      'RU',
      'SA',
      'SE',
      'SG',
      'SI',
      'SK',
      'SV',
      'TH',
      'TN',
      'TR',
      'TW',
      'UA',
      'US',
      'UY',
      'VN',
      'XK',
      'ZA'
    ],
    external_urls: {
      spotify: 'https://open.spotify.com/album/1pw5musYA2A2FWpswW9rzK'
    },
    href: 'https://api.spotify.com/v1/albums/1pw5musYA2A2FWpswW9rzK',
    id: '1pw5musYA2A2FWpswW9rzK',
    images: [
      {
        height: 640,
        url: 'https://i.scdn.co/image/ab67616d0000b27395c1887d5dc64a7f28f32447',
        width: 640
      },
      {
        height: 300,
        url: 'https://i.scdn.co/image/ab67616d00001e0295c1887d5dc64a7f28f32447',
        width: 300
      },
      {
        height: 64,
        url: 'https://i.scdn.co/image/ab67616d0000485195c1887d5dc64a7f28f32447',
        width: 64
      }
    ],
    name: 'Mercy',
    release_date: '2021-02-05',
    release_date_precision: 'day',
    total_tracks: 1,
    type: 'album',
    uri: 'spotify:album:1pw5musYA2A2FWpswW9rzK'
  },
  {
    album_type: 'single',
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/5CiGnKThu5ctn9pBxv7DGa'
        },
        href: 'https://api.spotify.com/v1/artists/5CiGnKThu5ctn9pBxv7DGa',
        id: '5CiGnKThu5ctn9pBxv7DGa',
        name: 'benny blanco',
        type: 'artist',
        uri: 'spotify:artist:5CiGnKThu5ctn9pBxv7DGa'
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/64KEffDW9EtZ1y2vBYgq8T'
        },
        href: 'https://api.spotify.com/v1/artists/64KEffDW9EtZ1y2vBYgq8T',
        id: '64KEffDW9EtZ1y2vBYgq8T',
        name: 'Marshmello',
        type: 'artist',
        uri: 'spotify:artist:64KEffDW9EtZ1y2vBYgq8T'
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/10exVja0key0uqUkk6LJRT'
        },
        href: 'https://api.spotify.com/v1/artists/10exVja0key0uqUkk6LJRT',
        id: '10exVja0key0uqUkk6LJRT',
        name: 'Vance Joy',
        type: 'artist',
        uri: 'spotify:artist:10exVja0key0uqUkk6LJRT'
      }
    ],
    available_markets: [
      'AD',
      'AE',
      'AL',
      'AR',
      'AT',
      'AU',
      'BA',
      'BE',
      'BG',
      'BH',
      'BO',
      'BR',
      'BY',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'GT',
      'HK',
      'HN',
      'HR',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IS',
      'IT',
      'JO',
      'JP',
      'KR',
      'KW',
      'KZ',
      'LB',
      'LI',
      'LT',
      'LU',
      'LV',
      'MA',
      'MC',
      'MD',
      'ME',
      'MK',
      'MT',
      'MX',
      'MY',
      'NI',
      'NL',
      'NO',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PH',
      'PL',
      'PS',
      'PT',
      'PY',
      'QA',
      'RO',
      'RS',
      'RU',
      'SA',
      'SE',
      'SG',
      'SI',
      'SK',
      'SV',
      'TH',
      'TN',
      'TR',
      'TW',
      'UA',
      'US',
      'UY',
      'VN',
      'XK',
      'ZA'
    ],
    external_urls: {
      spotify: 'https://open.spotify.com/album/3U75bXq9LhqZoaGoBCXikn'
    },
    href: 'https://api.spotify.com/v1/albums/3U75bXq9LhqZoaGoBCXikn',
    id: '3U75bXq9LhqZoaGoBCXikn',
    images: [
      {
        height: 640,
        url: 'https://i.scdn.co/image/ab67616d0000b27338e349efcd6a1c63e403b97f',
        width: 640
      },
      {
        height: 300,
        url: 'https://i.scdn.co/image/ab67616d00001e0238e349efcd6a1c63e403b97f',
        width: 300
      },
      {
        height: 64,
        url: 'https://i.scdn.co/image/ab67616d0000485138e349efcd6a1c63e403b97f',
        width: 64
      }
    ],
    name: 'You (with Marshmello & Vance Joy)',
    release_date: '2021-01-29',
    release_date_precision: 'day',
    total_tracks: 1,
    type: 'album',
    uri: 'spotify:album:3U75bXq9LhqZoaGoBCXikn'
  }
];

jest.mock('../../flux/actions/actions');

describe('Given the Recommendations component', () => {
  let container;
  beforeEach(() => {
    container = document.createElement('div');
    document.body.appendChild(container);
  });

  afterEach(() => {
    unmountComponentAtNode(container);
    container.remove();
  });

  describe('when the component is rendered', () => {
    test('A section is created with the appropiate className attribute', () => {
      act(() => {
        // eslint-disable-next-line react/jsx-filename-extension
        render(<Recommendations />, container);
      });
      const sectionClass = document.querySelector('section').className;

      expect(sectionClass).toBe('dashboard__recommendations');
    });
    describe('When loading for first time the component', () => {
      test('...covegare on map', () => {
        // eslint-disable-next-line max-len
        // Mockear acction loadFirstTime e invocarla aquí (fuera del act!)
        loadFirstTime.mockImplementation(() => {
          dispatcher.dispatch({
            type: actionTypes.LOAD_FIRST_TIME,
            data: mockData
          });
        });

        act(() => {
          loadFirstTime();
          // eslint-disable-next-line react/jsx-filename-extension

          render(<BrowserRouter>
            <Recommendations />
          </BrowserRouter>, container);
        });
        const sectionClass = document.querySelector('section').className;

        expect(sectionClass).toBe('dashboard__recommendations');
      });
    });
  });
});
