import React from 'react';
import { unmountComponentAtNode, render } from 'react-dom';
import { act } from 'react-dom/test-utils';
import { BrowserRouter } from 'react-router-dom';
import RecommendationsSeeds from './recommendations-seed';
import actionTypes from '../../flux/actions/actionTypes';

import dispatcher from '../../flux/dispatcher/dispatcher';

describe('Given the Recommendations component', () => {
  let container;
  beforeEach(() => {
    container = document.createElement('div');
    document.body.appendChild(container);
  });

  afterEach(() => {
    unmountComponentAtNode(container);
    container.remove();
  });

  describe('when the component is rendered after performing a search action', () => {
    test('A section is created with the appropiate className attribute after following the flux flow through the store', () => {
      const recommendationsSeed = [
        {
          album: {
            album_type: 'ALBUM',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/7gSjFKpVmDgC2MMsnN8CYq'
                },
                href: 'https://api.spotify.com/v1/artists/7gSjFKpVmDgC2MMsnN8CYq',
                id: '7gSjFKpVmDgC2MMsnN8CYq',
                name: 'Jazmine Sullivan',
                type: 'artist',
                uri: 'spotify:artist:7gSjFKpVmDgC2MMsnN8CYq'
              }
            ],
            available_markets: [
              'AD',
              'AE',
              'AL',
              'AR',
              'AT',
              'AU',
              'BA',
              'BE',
              'BG',
              'BH',
              'BO',
              'BR',
              'BY',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'DZ',
              'EC',
              'EE',
              'EG',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HR',
              'HU',
              'ID',
              'IE',
              'IL',
              'IN',
              'IS',
              'IT',
              'JO',
              'JP',
              'KR',
              'KW',
              'KZ',
              'LB',
              'LI',
              'LT',
              'LU',
              'LV',
              'MA',
              'MC',
              'MD',
              'ME',
              'MK',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'OM',
              'PA',
              'PE',
              'PH',
              'PL',
              'PS',
              'PT',
              'PY',
              'QA',
              'RO',
              'RS',
              'RU',
              'SA',
              'SE',
              'SG',
              'SI',
              'SK',
              'SV',
              'TH',
              'TN',
              'TR',
              'TW',
              'UA',
              'US',
              'UY',
              'VN',
              'XK',
              'ZA'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/682dnvSPZ6lwCNodfMVcbh'
            },
            href: 'https://api.spotify.com/v1/albums/682dnvSPZ6lwCNodfMVcbh',
            id: '682dnvSPZ6lwCNodfMVcbh',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/ab67616d0000b273554548a98bdf78e749b3a2f6',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/ab67616d00001e02554548a98bdf78e749b3a2f6',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/ab67616d00004851554548a98bdf78e749b3a2f6',
                width: 64
              }
            ],
            name: 'Reality Show',
            release_date: '2015-01-12',
            release_date_precision: 'day',
            total_tracks: 12,
            type: 'album',
            uri: 'spotify:album:682dnvSPZ6lwCNodfMVcbh'
          },
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/7gSjFKpVmDgC2MMsnN8CYq'
              },
              href: 'https://api.spotify.com/v1/artists/7gSjFKpVmDgC2MMsnN8CYq',
              id: '7gSjFKpVmDgC2MMsnN8CYq',
              name: 'Jazmine Sullivan',
              type: 'artist',
              uri: 'spotify:artist:7gSjFKpVmDgC2MMsnN8CYq'
            }
          ],
          available_markets: [
            'AD',
            'AE',
            'AL',
            'AR',
            'AT',
            'AU',
            'BA',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'BY',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HR',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KR',
            'KW',
            'KZ',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MD',
            'ME',
            'MK',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'RS',
            'RU',
            'SA',
            'SE',
            'SG',
            'SI',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'UA',
            'US',
            'UY',
            'VN',
            'XK',
            'ZA'
          ],
          disc_number: 1,
          duration_ms: 219493,
          explicit: false,
          external_ids: {
            isrc: 'USRC11401536'
          },
          external_urls: {
            spotify: 'https://open.spotify.com/track/37uAnLoFKVS5ttugqPuWIm'
          },
          href: 'https://api.spotify.com/v1/tracks/37uAnLoFKVS5ttugqPuWIm',
          id: '37uAnLoFKVS5ttugqPuWIm',
          is_local: false,
          name: "Forever Don't Last",
          popularity: 45,
          preview_url: 'https://p.scdn.co/mp3-preview/c2a7c8661fac2f6d2d3fd36769326f6f05eb3d66?cid=774b29d4f13844c495f206cafdad9c86',
          track_number: 8,
          type: 'track',
          uri: 'spotify:track:37uAnLoFKVS5ttugqPuWIm'
        },
        {
          album: {
            album_type: 'ALBUM',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/3UjPnt2nRmw10N58bBeNOg'
                },
                href: 'https://api.spotify.com/v1/artists/3UjPnt2nRmw10N58bBeNOg',
                id: '3UjPnt2nRmw10N58bBeNOg',
                name: 'Xavier Omär',
                type: 'artist',
                uri: 'spotify:artist:3UjPnt2nRmw10N58bBeNOg'
              },
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/7e3FtKBIPLrIVm8g1FJMVg'
                },
                href: 'https://api.spotify.com/v1/artists/7e3FtKBIPLrIVm8g1FJMVg',
                id: '7e3FtKBIPLrIVm8g1FJMVg',
                name: 'Sango',
                type: 'artist',
                uri: 'spotify:artist:7e3FtKBIPLrIVm8g1FJMVg'
              }
            ],
            available_markets: [
              'AD',
              'AE',
              'AL',
              'AR',
              'AT',
              'AU',
              'BA',
              'BE',
              'BG',
              'BH',
              'BO',
              'BR',
              'BY',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'DZ',
              'EC',
              'EE',
              'EG',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HR',
              'HU',
              'ID',
              'IE',
              'IL',
              'IN',
              'IS',
              'IT',
              'JO',
              'JP',
              'KR',
              'KW',
              'KZ',
              'LB',
              'LI',
              'LT',
              'LU',
              'LV',
              'MA',
              'MC',
              'MD',
              'ME',
              'MK',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'OM',
              'PA',
              'PE',
              'PH',
              'PL',
              'PS',
              'PT',
              'PY',
              'QA',
              'RO',
              'RS',
              'RU',
              'SA',
              'SE',
              'SG',
              'SI',
              'SK',
              'SV',
              'TH',
              'TN',
              'TR',
              'TW',
              'UA',
              'US',
              'UY',
              'VN',
              'XK',
              'ZA'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/2m8sIT1YP8YBQm2MAliBAH'
            },
            href: 'https://api.spotify.com/v1/albums/2m8sIT1YP8YBQm2MAliBAH',
            id: '2m8sIT1YP8YBQm2MAliBAH',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/ab67616d0000b273dc6474af51185f072f67767b',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/ab67616d00001e02dc6474af51185f072f67767b',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/ab67616d00004851dc6474af51185f072f67767b',
                width: 64
              }
            ],
            name: 'Moments Spent Loving You',
            release_date: '2019-10-25',
            release_date_precision: 'day',
            total_tracks: 11,
            type: 'album',
            uri: 'spotify:album:2m8sIT1YP8YBQm2MAliBAH'
          },
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/3UjPnt2nRmw10N58bBeNOg'
              },
              href: 'https://api.spotify.com/v1/artists/3UjPnt2nRmw10N58bBeNOg',
              id: '3UjPnt2nRmw10N58bBeNOg',
              name: 'Xavier Omär',
              type: 'artist',
              uri: 'spotify:artist:3UjPnt2nRmw10N58bBeNOg'
            },
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/7e3FtKBIPLrIVm8g1FJMVg'
              },
              href: 'https://api.spotify.com/v1/artists/7e3FtKBIPLrIVm8g1FJMVg',
              id: '7e3FtKBIPLrIVm8g1FJMVg',
              name: 'Sango',
              type: 'artist',
              uri: 'spotify:artist:7e3FtKBIPLrIVm8g1FJMVg'
            }
          ],
          available_markets: [
            'AD',
            'AE',
            'AL',
            'AR',
            'AT',
            'AU',
            'BA',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'BY',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HR',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KR',
            'KW',
            'KZ',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MD',
            'ME',
            'MK',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'RS',
            'RU',
            'SA',
            'SE',
            'SG',
            'SI',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'UA',
            'US',
            'UY',
            'VN',
            'XK',
            'ZA'
          ],
          disc_number: 1,
          duration_ms: 218226,
          explicit: false,
          external_ids: {
            isrc: 'USRC11902868'
          },
          external_urls: {
            spotify: 'https://open.spotify.com/track/6iCFFLe0WjnKUkf0PMD3xO'
          },
          href: 'https://api.spotify.com/v1/tracks/6iCFFLe0WjnKUkf0PMD3xO',
          id: '6iCFFLe0WjnKUkf0PMD3xO',
          is_local: false,
          name: 'Deep End',
          popularity: 42,
          preview_url: 'https://p.scdn.co/mp3-preview/f8ad9b1d388f4e6216557f9694ded9513e2b7497?cid=774b29d4f13844c495f206cafdad9c86',
          track_number: 1,
          type: 'track',
          uri: 'spotify:track:6iCFFLe0WjnKUkf0PMD3xO'
        },
        {
          album: {
            album_type: 'ALBUM',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/60ciIY5MouLc2Y9n34DJdA'
                },
                href: 'https://api.spotify.com/v1/artists/60ciIY5MouLc2Y9n34DJdA',
                id: '60ciIY5MouLc2Y9n34DJdA',
                name: 'Ledisi',
                type: 'artist',
                uri: 'spotify:artist:60ciIY5MouLc2Y9n34DJdA'
              }
            ],
            available_markets: [
              'AD',
              'AE',
              'AL',
              'AR',
              'AT',
              'AU',
              'BA',
              'BE',
              'BG',
              'BH',
              'BO',
              'BR',
              'BY',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'DZ',
              'EC',
              'EE',
              'EG',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HR',
              'HU',
              'ID',
              'IE',
              'IL',
              'IN',
              'IS',
              'IT',
              'JO',
              'JP',
              'KR',
              'KW',
              'KZ',
              'LB',
              'LI',
              'LT',
              'LU',
              'LV',
              'MA',
              'MC',
              'MD',
              'ME',
              'MK',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'OM',
              'PA',
              'PE',
              'PH',
              'PL',
              'PS',
              'PT',
              'PY',
              'QA',
              'RO',
              'RS',
              'RU',
              'SA',
              'SE',
              'SG',
              'SI',
              'SK',
              'SV',
              'TH',
              'TN',
              'TR',
              'TW',
              'UA',
              'US',
              'UY',
              'VN',
              'XK',
              'ZA'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/0YtU2YYjqJv8E0MAePFpom'
            },
            href: 'https://api.spotify.com/v1/albums/0YtU2YYjqJv8E0MAePFpom',
            id: '0YtU2YYjqJv8E0MAePFpom',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/ab67616d0000b27373b914578aa082453bd0b0d3',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/ab67616d00001e0273b914578aa082453bd0b0d3',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/ab67616d0000485173b914578aa082453bd0b0d3',
                width: 64
              }
            ],
            name: 'Let Love Rule',
            release_date: '2017-09-22',
            release_date_precision: 'day',
            total_tracks: 15,
            type: 'album',
            uri: 'spotify:album:0YtU2YYjqJv8E0MAePFpom'
          },
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/60ciIY5MouLc2Y9n34DJdA'
              },
              href: 'https://api.spotify.com/v1/artists/60ciIY5MouLc2Y9n34DJdA',
              id: '60ciIY5MouLc2Y9n34DJdA',
              name: 'Ledisi',
              type: 'artist',
              uri: 'spotify:artist:60ciIY5MouLc2Y9n34DJdA'
            }
          ],
          available_markets: [
            'AD',
            'AE',
            'AL',
            'AR',
            'AT',
            'AU',
            'BA',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'BY',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HR',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KR',
            'KW',
            'KZ',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MD',
            'ME',
            'MK',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'RS',
            'RU',
            'SA',
            'SE',
            'SG',
            'SI',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'UA',
            'US',
            'UY',
            'VN',
            'XK',
            'ZA'
          ],
          disc_number: 1,
          duration_ms: 302413,
          explicit: false,
          external_ids: {
            isrc: 'USUM71707450'
          },
          external_urls: {
            spotify: 'https://open.spotify.com/track/6MLyrHJWiEjDlA1fuPlxrd'
          },
          href: 'https://api.spotify.com/v1/tracks/6MLyrHJWiEjDlA1fuPlxrd',
          id: '6MLyrHJWiEjDlA1fuPlxrd',
          is_local: false,
          name: 'All The Way',
          popularity: 43,
          preview_url: null,
          track_number: 14,
          type: 'track',
          uri: 'spotify:track:6MLyrHJWiEjDlA1fuPlxrd'
        },
        {
          album: {
            album_type: 'ALBUM',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/63XBtGSEZINSyXylZxEUbv'
                },
                href: 'https://api.spotify.com/v1/artists/63XBtGSEZINSyXylZxEUbv',
                id: '63XBtGSEZINSyXylZxEUbv',
                name: 'Victoria Monét',
                type: 'artist',
                uri: 'spotify:artist:63XBtGSEZINSyXylZxEUbv'
              }
            ],
            available_markets: [
              'AD',
              'AE',
              'AL',
              'AR',
              'AT',
              'AU',
              'BA',
              'BE',
              'BG',
              'BH',
              'BO',
              'BR',
              'BY',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'DZ',
              'EC',
              'EE',
              'EG',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HR',
              'HU',
              'ID',
              'IE',
              'IL',
              'IN',
              'IS',
              'IT',
              'JO',
              'JP',
              'KR',
              'KW',
              'KZ',
              'LB',
              'LI',
              'LT',
              'LU',
              'LV',
              'MA',
              'MC',
              'MD',
              'ME',
              'MK',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'OM',
              'PA',
              'PE',
              'PH',
              'PL',
              'PS',
              'PT',
              'PY',
              'QA',
              'RO',
              'RS',
              'RU',
              'SA',
              'SE',
              'SG',
              'SI',
              'SK',
              'SV',
              'TH',
              'TN',
              'TR',
              'TW',
              'UA',
              'US',
              'UY',
              'VN',
              'XK',
              'ZA'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/6aW67R0sshdUwtbJEG2uQR'
            },
            href: 'https://api.spotify.com/v1/albums/6aW67R0sshdUwtbJEG2uQR',
            id: '6aW67R0sshdUwtbJEG2uQR',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/ab67616d0000b27350aa87e1dea05ba3155bbbb2',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/ab67616d00001e0250aa87e1dea05ba3155bbbb2',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/ab67616d0000485150aa87e1dea05ba3155bbbb2',
                width: 64
              }
            ],
            name: 'JAGUAR',
            release_date: '2020-08-07',
            release_date_precision: 'day',
            total_tracks: 9,
            type: 'album',
            uri: 'spotify:album:6aW67R0sshdUwtbJEG2uQR'
          },
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/63XBtGSEZINSyXylZxEUbv'
              },
              href: 'https://api.spotify.com/v1/artists/63XBtGSEZINSyXylZxEUbv',
              id: '63XBtGSEZINSyXylZxEUbv',
              name: 'Victoria Monét',
              type: 'artist',
              uri: 'spotify:artist:63XBtGSEZINSyXylZxEUbv'
            },
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/6LuN9FCkKOj5PcnpouEgny'
              },
              href: 'https://api.spotify.com/v1/artists/6LuN9FCkKOj5PcnpouEgny',
              id: '6LuN9FCkKOj5PcnpouEgny',
              name: 'Khalid',
              type: 'artist',
              uri: 'spotify:artist:6LuN9FCkKOj5PcnpouEgny'
            },
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/0GG2cWaonE4JPrjcCCQ1EG'
              },
              href: 'https://api.spotify.com/v1/artists/0GG2cWaonE4JPrjcCCQ1EG',
              id: '0GG2cWaonE4JPrjcCCQ1EG',
              name: 'SG Lewis',
              type: 'artist',
              uri: 'spotify:artist:0GG2cWaonE4JPrjcCCQ1EG'
            }
          ],
          available_markets: [
            'AD',
            'AE',
            'AL',
            'AR',
            'AT',
            'AU',
            'BA',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'BY',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HR',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KR',
            'KW',
            'KZ',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MD',
            'ME',
            'MK',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'RS',
            'RU',
            'SA',
            'SE',
            'SG',
            'SI',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'UA',
            'US',
            'UY',
            'VN',
            'XK',
            'ZA'
          ],
          disc_number: 1,
          duration_ms: 176773,
          explicit: false,
          external_ids: {
            isrc: 'US23A1512007'
          },
          external_urls: {
            spotify: 'https://open.spotify.com/track/2oap3QptGISyIvwKpnJJId'
          },
          href: 'https://api.spotify.com/v1/tracks/2oap3QptGISyIvwKpnJJId',
          id: '2oap3QptGISyIvwKpnJJId',
          is_local: false,
          name: 'Experience',
          popularity: 61,
          preview_url: 'https://p.scdn.co/mp3-preview/b05c861ba0819e9d3638fa1ce5e54e6a970cd245?cid=774b29d4f13844c495f206cafdad9c86',
          track_number: 6,
          type: 'track',
          uri: 'spotify:track:2oap3QptGISyIvwKpnJJId'
        },
        {
          album: {
            album_type: 'SINGLE',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/77SLhlrrJKzclwLB9bnRJZ'
                },
                href: 'https://api.spotify.com/v1/artists/77SLhlrrJKzclwLB9bnRJZ',
                id: '77SLhlrrJKzclwLB9bnRJZ',
                name: 'Alex Mali',
                type: 'artist',
                uri: 'spotify:artist:77SLhlrrJKzclwLB9bnRJZ'
              }
            ],
            available_markets: [
              'AD',
              'AE',
              'AL',
              'AR',
              'AT',
              'AU',
              'BA',
              'BE',
              'BG',
              'BH',
              'BO',
              'BR',
              'BY',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'DZ',
              'EC',
              'EE',
              'EG',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HR',
              'HU',
              'ID',
              'IE',
              'IL',
              'IN',
              'IS',
              'IT',
              'JO',
              'JP',
              'KR',
              'KW',
              'KZ',
              'LB',
              'LI',
              'LT',
              'LU',
              'LV',
              'MA',
              'MC',
              'MD',
              'ME',
              'MK',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'OM',
              'PA',
              'PE',
              'PH',
              'PL',
              'PS',
              'PT',
              'PY',
              'QA',
              'RO',
              'RS',
              'RU',
              'SA',
              'SE',
              'SG',
              'SI',
              'SK',
              'SV',
              'TH',
              'TN',
              'TR',
              'TW',
              'UA',
              'US',
              'UY',
              'VN',
              'XK',
              'ZA'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/6NGERRIdmgyfMw9ESerlZE'
            },
            href: 'https://api.spotify.com/v1/albums/6NGERRIdmgyfMw9ESerlZE',
            id: '6NGERRIdmgyfMw9ESerlZE',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/ab67616d0000b2739877588edf6d52fb88ce4158',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/ab67616d00001e029877588edf6d52fb88ce4158',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/ab67616d000048519877588edf6d52fb88ce4158',
                width: 64
              }
            ],
            name: 'Sweet & Sour - EP',
            release_date: '2019-07-26',
            release_date_precision: 'day',
            total_tracks: 6,
            type: 'album',
            uri: 'spotify:album:6NGERRIdmgyfMw9ESerlZE'
          },
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/77SLhlrrJKzclwLB9bnRJZ'
              },
              href: 'https://api.spotify.com/v1/artists/77SLhlrrJKzclwLB9bnRJZ',
              id: '77SLhlrrJKzclwLB9bnRJZ',
              name: 'Alex Mali',
              type: 'artist',
              uri: 'spotify:artist:77SLhlrrJKzclwLB9bnRJZ'
            }
          ],
          available_markets: [
            'AD',
            'AE',
            'AL',
            'AR',
            'AT',
            'AU',
            'BA',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'BY',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HR',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KR',
            'KW',
            'KZ',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MD',
            'ME',
            'MK',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'RS',
            'RU',
            'SA',
            'SE',
            'SG',
            'SI',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'UA',
            'US',
            'UY',
            'VN',
            'XK',
            'ZA'
          ],
          disc_number: 1,
          duration_ms: 234352,
          explicit: false,
          external_ids: {
            isrc: 'USUYG1261409'
          },
          external_urls: {
            spotify: 'https://open.spotify.com/track/5mwSU8en1165SVwnYHe8Kz'
          },
          href: 'https://api.spotify.com/v1/tracks/5mwSU8en1165SVwnYHe8Kz',
          id: '5mwSU8en1165SVwnYHe8Kz',
          is_local: false,
          name: 'Obviously',
          popularity: 49,
          preview_url: 'https://p.scdn.co/mp3-preview/3c5c5eed31758559085e22905e2bf87f7398078d?cid=774b29d4f13844c495f206cafdad9c86',
          track_number: 6,
          type: 'track',
          uri: 'spotify:track:5mwSU8en1165SVwnYHe8Kz'
        },
        {
          album: {
            album_type: 'ALBUM',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/7E2ioKxoxI2J94tUkIx6As'
                },
                href: 'https://api.spotify.com/v1/artists/7E2ioKxoxI2J94tUkIx6As',
                id: '7E2ioKxoxI2J94tUkIx6As',
                name: 'Alex Isley',
                type: 'artist',
                uri: 'spotify:artist:7E2ioKxoxI2J94tUkIx6As'
              }
            ],
            available_markets: [
              'AD',
              'AE',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BH',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'DZ',
              'EC',
              'EE',
              'EG',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IL',
              'IN',
              'IS',
              'IT',
              'JO',
              'JP',
              'KR',
              'KW',
              'KZ',
              'LB',
              'LI',
              'LT',
              'LU',
              'LV',
              'MA',
              'MC',
              'MD',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'OM',
              'PA',
              'PE',
              'PH',
              'PL',
              'PS',
              'PT',
              'PY',
              'QA',
              'RO',
              'RU',
              'SA',
              'SE',
              'SG',
              'SI',
              'SK',
              'SV',
              'TH',
              'TN',
              'TR',
              'TW',
              'UA',
              'US',
              'UY',
              'VN',
              'ZA'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/2IzV3QlV29G5V1AnKMHmAg'
            },
            href: 'https://api.spotify.com/v1/albums/2IzV3QlV29G5V1AnKMHmAg',
            id: '2IzV3QlV29G5V1AnKMHmAg',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/ab67616d0000b273b95f532a81fc54fe4415b81c',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/ab67616d00001e02b95f532a81fc54fe4415b81c',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/ab67616d00004851b95f532a81fc54fe4415b81c',
                width: 64
              }
            ],
            name: 'Dreams in Analog',
            release_date: '2013-08-10',
            release_date_precision: 'day',
            total_tracks: 9,
            type: 'album',
            uri: 'spotify:album:2IzV3QlV29G5V1AnKMHmAg'
          },
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/7E2ioKxoxI2J94tUkIx6As'
              },
              href: 'https://api.spotify.com/v1/artists/7E2ioKxoxI2J94tUkIx6As',
              id: '7E2ioKxoxI2J94tUkIx6As',
              name: 'Alex Isley',
              type: 'artist',
              uri: 'spotify:artist:7E2ioKxoxI2J94tUkIx6As'
            }
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KR',
            'KW',
            'KZ',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MD',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'RU',
            'SA',
            'SE',
            'SG',
            'SI',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'UA',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          disc_number: 1,
          duration_ms: 287059,
          explicit: false,
          external_ids: {
            isrc: 'TCADG1764101'
          },
          external_urls: {
            spotify: 'https://open.spotify.com/track/3eDRjkhT93bg7Kjp66uXPw'
          },
          href: 'https://api.spotify.com/v1/tracks/3eDRjkhT93bg7Kjp66uXPw',
          id: '3eDRjkhT93bg7Kjp66uXPw',
          is_local: false,
          name: 'About Him',
          popularity: 48,
          preview_url: 'https://p.scdn.co/mp3-preview/ed7a34955186c248a127676e27eb429ebee6968f?cid=774b29d4f13844c495f206cafdad9c86',
          track_number: 8,
          type: 'track',
          uri: 'spotify:track:3eDRjkhT93bg7Kjp66uXPw'
        },
        {
          album: {
            album_type: 'SINGLE',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/3UjPnt2nRmw10N58bBeNOg'
                },
                href: 'https://api.spotify.com/v1/artists/3UjPnt2nRmw10N58bBeNOg',
                id: '3UjPnt2nRmw10N58bBeNOg',
                name: 'Xavier Omär',
                type: 'artist',
                uri: 'spotify:artist:3UjPnt2nRmw10N58bBeNOg'
              }
            ],
            available_markets: [
              'AD',
              'AE',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BH',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'DZ',
              'EC',
              'EE',
              'EG',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IL',
              'IN',
              'IS',
              'IT',
              'JO',
              'JP',
              'KR',
              'KW',
              'KZ',
              'LB',
              'LI',
              'LT',
              'LU',
              'LV',
              'MA',
              'MC',
              'MD',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'OM',
              'PA',
              'PE',
              'PH',
              'PL',
              'PS',
              'PT',
              'PY',
              'QA',
              'RO',
              'RU',
              'SA',
              'SE',
              'SG',
              'SI',
              'SK',
              'SV',
              'TH',
              'TN',
              'TR',
              'TW',
              'UA',
              'US',
              'UY',
              'VN',
              'ZA'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/5VjgE3Mjh32oW42Y5ku6Ea'
            },
            href: 'https://api.spotify.com/v1/albums/5VjgE3Mjh32oW42Y5ku6Ea',
            id: '5VjgE3Mjh32oW42Y5ku6Ea',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/ab67616d0000b2736e80b9c092c8c420ea51ce98',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/ab67616d00001e026e80b9c092c8c420ea51ce98',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/ab67616d000048516e80b9c092c8c420ea51ce98',
                width: 64
              }
            ],
            name: 'Honest',
            release_date: '2016-06-11',
            release_date_precision: 'day',
            total_tracks: 1,
            type: 'album',
            uri: 'spotify:album:5VjgE3Mjh32oW42Y5ku6Ea'
          },
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/3UjPnt2nRmw10N58bBeNOg'
              },
              href: 'https://api.spotify.com/v1/artists/3UjPnt2nRmw10N58bBeNOg',
              id: '3UjPnt2nRmw10N58bBeNOg',
              name: 'Xavier Omär',
              type: 'artist',
              uri: 'spotify:artist:3UjPnt2nRmw10N58bBeNOg'
            }
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KR',
            'KW',
            'KZ',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MD',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'RU',
            'SA',
            'SE',
            'SG',
            'SI',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'UA',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          disc_number: 1,
          duration_ms: 170248,
          explicit: false,
          external_ids: {
            isrc: 'TCACP1627943'
          },
          external_urls: {
            spotify: 'https://open.spotify.com/track/7rezT408cCLBBr40Gvtg4J'
          },
          href: 'https://api.spotify.com/v1/tracks/7rezT408cCLBBr40Gvtg4J',
          id: '7rezT408cCLBBr40Gvtg4J',
          is_local: false,
          name: 'Honest',
          popularity: 44,
          preview_url: 'https://p.scdn.co/mp3-preview/6e728b9d0fcb656c40e7102848c8fb2b58ab79ac?cid=774b29d4f13844c495f206cafdad9c86',
          track_number: 1,
          type: 'track',
          uri: 'spotify:track:7rezT408cCLBBr40Gvtg4J'
        },
        {
          album: {
            album_type: 'ALBUM',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/7gSjFKpVmDgC2MMsnN8CYq'
                },
                href: 'https://api.spotify.com/v1/artists/7gSjFKpVmDgC2MMsnN8CYq',
                id: '7gSjFKpVmDgC2MMsnN8CYq',
                name: 'Jazmine Sullivan',
                type: 'artist',
                uri: 'spotify:artist:7gSjFKpVmDgC2MMsnN8CYq'
              }
            ],
            available_markets: [
              'AD',
              'AE',
              'AL',
              'AR',
              'AT',
              'AU',
              'BA',
              'BE',
              'BG',
              'BH',
              'BO',
              'BR',
              'BY',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'DZ',
              'EC',
              'EE',
              'EG',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HR',
              'HU',
              'ID',
              'IE',
              'IL',
              'IN',
              'IS',
              'IT',
              'JO',
              'JP',
              'KR',
              'KW',
              'KZ',
              'LB',
              'LI',
              'LT',
              'LU',
              'LV',
              'MA',
              'MC',
              'MD',
              'ME',
              'MK',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'OM',
              'PA',
              'PE',
              'PH',
              'PL',
              'PS',
              'PT',
              'PY',
              'QA',
              'RO',
              'RS',
              'RU',
              'SA',
              'SE',
              'SG',
              'SI',
              'SK',
              'SV',
              'TH',
              'TN',
              'TR',
              'TW',
              'UA',
              'US',
              'UY',
              'VN',
              'XK',
              'ZA'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/682dnvSPZ6lwCNodfMVcbh'
            },
            href: 'https://api.spotify.com/v1/albums/682dnvSPZ6lwCNodfMVcbh',
            id: '682dnvSPZ6lwCNodfMVcbh',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/ab67616d0000b273554548a98bdf78e749b3a2f6',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/ab67616d00001e02554548a98bdf78e749b3a2f6',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/ab67616d00004851554548a98bdf78e749b3a2f6',
                width: 64
              }
            ],
            name: 'Reality Show',
            release_date: '2015-01-12',
            release_date_precision: 'day',
            total_tracks: 12,
            type: 'album',
            uri: 'spotify:album:682dnvSPZ6lwCNodfMVcbh'
          },
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/7gSjFKpVmDgC2MMsnN8CYq'
              },
              href: 'https://api.spotify.com/v1/artists/7gSjFKpVmDgC2MMsnN8CYq',
              id: '7gSjFKpVmDgC2MMsnN8CYq',
              name: 'Jazmine Sullivan',
              type: 'artist',
              uri: 'spotify:artist:7gSjFKpVmDgC2MMsnN8CYq'
            }
          ],
          available_markets: [
            'AD',
            'AE',
            'AL',
            'AR',
            'AT',
            'AU',
            'BA',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'BY',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HR',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KR',
            'KW',
            'KZ',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MD',
            'ME',
            'MK',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'RS',
            'RU',
            'SA',
            'SE',
            'SG',
            'SI',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'UA',
            'US',
            'UY',
            'VN',
            'XK',
            'ZA'
          ],
          disc_number: 1,
          duration_ms: 223093,
          explicit: true,
          external_ids: {
            isrc: 'USRC11401534'
          },
          external_urls: {
            spotify: 'https://open.spotify.com/track/6KOc6ViZB8NtfCVABmTe66'
          },
          href: 'https://api.spotify.com/v1/tracks/6KOc6ViZB8NtfCVABmTe66',
          id: '6KOc6ViZB8NtfCVABmTe66',
          is_local: false,
          name: 'Let It Burn',
          popularity: 58,
          preview_url: 'https://p.scdn.co/mp3-preview/fe02200ea24d04b4b99d5dea21c6253215347cd1?cid=774b29d4f13844c495f206cafdad9c86',
          track_number: 6,
          type: 'track',
          uri: 'spotify:track:6KOc6ViZB8NtfCVABmTe66'
        },
        {
          album: {
            album_type: 'ALBUM',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/5lcDGoJUr5WY5bCFAfYbCU'
                },
                href: 'https://api.spotify.com/v1/artists/5lcDGoJUr5WY5bCFAfYbCU',
                id: '5lcDGoJUr5WY5bCFAfYbCU',
                name: 'KIRBY',
                type: 'artist',
                uri: 'spotify:artist:5lcDGoJUr5WY5bCFAfYbCU'
              }
            ],
            available_markets: [
              'AD',
              'AE',
              'AL',
              'AR',
              'AT',
              'AU',
              'BA',
              'BE',
              'BG',
              'BH',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'DZ',
              'EC',
              'EE',
              'EG',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HR',
              'HU',
              'ID',
              'IE',
              'IL',
              'IN',
              'IS',
              'IT',
              'JO',
              'JP',
              'KR',
              'KW',
              'KZ',
              'LB',
              'LI',
              'LT',
              'LU',
              'LV',
              'MA',
              'MC',
              'MD',
              'ME',
              'MK',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'OM',
              'PA',
              'PE',
              'PH',
              'PL',
              'PS',
              'PT',
              'PY',
              'QA',
              'RO',
              'RU',
              'SA',
              'SE',
              'SG',
              'SI',
              'SK',
              'SV',
              'TH',
              'TN',
              'TR',
              'TW',
              'UA',
              'US',
              'UY',
              'VN',
              'ZA'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/5udBfaGdflGiQRkL9TORN2'
            },
            href: 'https://api.spotify.com/v1/albums/5udBfaGdflGiQRkL9TORN2',
            id: '5udBfaGdflGiQRkL9TORN2',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/ab67616d0000b2737387dc1f6a5db68647337433',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/ab67616d00001e027387dc1f6a5db68647337433',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/ab67616d000048517387dc1f6a5db68647337433',
                width: 64
              }
            ],
            name: 'Sis.',
            release_date: '2020-01-31',
            release_date_precision: 'day',
            total_tracks: 7,
            type: 'album',
            uri: 'spotify:album:5udBfaGdflGiQRkL9TORN2'
          },
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/5lcDGoJUr5WY5bCFAfYbCU'
              },
              href: 'https://api.spotify.com/v1/artists/5lcDGoJUr5WY5bCFAfYbCU',
              id: '5lcDGoJUr5WY5bCFAfYbCU',
              name: 'KIRBY',
              type: 'artist',
              uri: 'spotify:artist:5lcDGoJUr5WY5bCFAfYbCU'
            }
          ],
          available_markets: [
            'AD',
            'AE',
            'AL',
            'AR',
            'AT',
            'AU',
            'BA',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HR',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KR',
            'KW',
            'KZ',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MD',
            'ME',
            'MK',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'RU',
            'SA',
            'SE',
            'SG',
            'SI',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'UA',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          disc_number: 1,
          duration_ms: 216523,
          explicit: false,
          external_ids: {
            isrc: 'TCAEP2058962'
          },
          external_urls: {
            spotify: 'https://open.spotify.com/track/67NvBpt8ZEJKGs9MCIUy4x'
          },
          href: 'https://api.spotify.com/v1/tracks/67NvBpt8ZEJKGs9MCIUy4x',
          id: '67NvBpt8ZEJKGs9MCIUy4x',
          is_local: false,
          name: 'Velvet',
          popularity: 45,
          preview_url: 'https://p.scdn.co/mp3-preview/ad12a3d0221155eb7bb9ba72fbab53ca809313a5?cid=774b29d4f13844c495f206cafdad9c86',
          track_number: 3,
          type: 'track',
          uri: 'spotify:track:67NvBpt8ZEJKGs9MCIUy4x'
        },
        {
          album: {
            album_type: 'ALBUM',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/5Vuvs6Py2JRU7WiFDVsI7J'
                },
                href: 'https://api.spotify.com/v1/artists/5Vuvs6Py2JRU7WiFDVsI7J',
                id: '5Vuvs6Py2JRU7WiFDVsI7J',
                name: 'Lucky Daye',
                type: 'artist',
                uri: 'spotify:artist:5Vuvs6Py2JRU7WiFDVsI7J'
              }
            ],
            available_markets: [
              'AD',
              'AE',
              'AL',
              'AR',
              'AT',
              'AU',
              'BA',
              'BE',
              'BG',
              'BH',
              'BO',
              'BR',
              'BY',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'DZ',
              'EC',
              'EE',
              'EG',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HR',
              'HU',
              'ID',
              'IE',
              'IL',
              'IN',
              'IS',
              'IT',
              'JO',
              'JP',
              'KR',
              'KW',
              'KZ',
              'LB',
              'LI',
              'LT',
              'LU',
              'LV',
              'MA',
              'MC',
              'MD',
              'ME',
              'MK',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'OM',
              'PA',
              'PE',
              'PH',
              'PL',
              'PS',
              'PT',
              'PY',
              'QA',
              'RO',
              'RS',
              'RU',
              'SA',
              'SE',
              'SG',
              'SI',
              'SK',
              'SV',
              'TH',
              'TN',
              'TR',
              'TW',
              'UA',
              'US',
              'UY',
              'VN',
              'XK',
              'ZA'
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/0sxfu0XUwHOtnKiZgkTQwk'
            },
            href: 'https://api.spotify.com/v1/albums/0sxfu0XUwHOtnKiZgkTQwk',
            id: '0sxfu0XUwHOtnKiZgkTQwk',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/ab67616d0000b273fe1c22315738dd6e313e400f',
                width: 640
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/ab67616d00001e02fe1c22315738dd6e313e400f',
                width: 300
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/ab67616d00004851fe1c22315738dd6e313e400f',
                width: 64
              }
            ],
            name: 'Painted',
            release_date: '2019-05-24',
            release_date_precision: 'day',
            total_tracks: 13,
            type: 'album',
            uri: 'spotify:album:0sxfu0XUwHOtnKiZgkTQwk'
          },
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/5Vuvs6Py2JRU7WiFDVsI7J'
              },
              href: 'https://api.spotify.com/v1/artists/5Vuvs6Py2JRU7WiFDVsI7J',
              id: '5Vuvs6Py2JRU7WiFDVsI7J',
              name: 'Lucky Daye',
              type: 'artist',
              uri: 'spotify:artist:5Vuvs6Py2JRU7WiFDVsI7J'
            }
          ],
          available_markets: [
            'AD',
            'AE',
            'AL',
            'AR',
            'AT',
            'AU',
            'BA',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'BY',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HR',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KR',
            'KW',
            'KZ',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MD',
            'ME',
            'MK',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'RS',
            'RU',
            'SA',
            'SE',
            'SG',
            'SI',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'UA',
            'US',
            'UY',
            'VN',
            'XK',
            'ZA'
          ],
          disc_number: 1,
          duration_ms: 216146,
          explicit: true,
          external_ids: {
            isrc: 'USRC11803591'
          },
          external_urls: {
            spotify: 'https://open.spotify.com/track/2RxbUs1UfebXymMwrAKZVB'
          },
          href: 'https://api.spotify.com/v1/tracks/2RxbUs1UfebXymMwrAKZVB',
          id: '2RxbUs1UfebXymMwrAKZVB',
          is_local: false,
          name: 'Concentrate',
          popularity: 43,
          preview_url: 'https://p.scdn.co/mp3-preview/359b3bafe032cb6d2e203dd0f477cc7e602c5fba?cid=774b29d4f13844c495f206cafdad9c86',
          track_number: 4,
          type: 'track',
          uri: 'spotify:track:2RxbUs1UfebXymMwrAKZVB'
        }
      ];

      const action = {
        type: actionTypes.SEARCH_RECOMMENDATIONS,
        data: recommendationsSeed
      };

      function searchRecommendations(actionToDispatch) {
        dispatcher.dispatch(actionToDispatch);
      }

      act(() => {
        // eslint-disable-next-line react/jsx-filename-extension
        render(<BrowserRouter>
          <RecommendationsSeeds />
        </BrowserRouter>, container);
      });
      searchRecommendations(action);
      const sectionClass = document.querySelector('section').className;

      expect(sectionClass).toBe('dashboard__recommendations');
    });
  });
});
