import React from 'react';
import { unmountComponentAtNode, render } from 'react-dom';
import { act } from 'react-dom/test-utils';
import { BrowserRouter } from 'react-router-dom';
import RecommendationsSeeds from './recommendations-seed';
import spotifindStore from '../../flux/stores/stores';

const mockData = [
  {
    album: {
      album_type: 'COMPILATION',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/43ZHCT0cAZBISjO8DG9PnE'
          },
          href: 'https://api.spotify.com/v1/artists/43ZHCT0cAZBISjO8DG9PnE',
          id: '43ZHCT0cAZBISjO8DG9PnE',
          name: 'Elvis Presley',
          type: 'artist',
          uri: 'spotify:artist:43ZHCT0cAZBISjO8DG9PnE'
        }
      ],
      available_markets: [
        'AD',
        'AE',
        'AL',
        'AR',
        'AT',
        'AU',
        'BA',
        'BE',
        'BG',
        'BH',
        'BO',
        'BR',
        'BY',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FR',
        'GB',
        'GR',
        'GT',
        'HK',
        'HN',
        'HR',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IS',
        'IT',
        'JO',
        'JP',
        'KR',
        'KW',
        'KZ',
        'LB',
        'LI',
        'LT',
        'LU',
        'LV',
        'MA',
        'MC',
        'MD',
        'ME',
        'MK',
        'MT',
        'MX',
        'MY',
        'NI',
        'NL',
        'NO',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PH',
        'PL',
        'PS',
        'PT',
        'PY',
        'QA',
        'RO',
        'RS',
        'RU',
        'SA',
        'SE',
        'SG',
        'SI',
        'SK',
        'SV',
        'TH',
        'TN',
        'TR',
        'TW',
        'UA',
        'US',
        'UY',
        'VN',
        'XK',
        'ZA'
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/5Iec810oL6PorbyBVjLnmD'
      },
      href: 'https://api.spotify.com/v1/albums/5Iec810oL6PorbyBVjLnmD',
      id: '5Iec810oL6PorbyBVjLnmD',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273a22455d1ff7031adeaa90a40',
          width: 640
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02a22455d1ff7031adeaa90a40',
          width: 300
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851a22455d1ff7031adeaa90a40',
          width: 64
        }
      ],
      name: "Elvis' Golden Records, Vol. 3",
      release_date: '1963-08-11',
      release_date_precision: 'day',
      total_tracks: 12,
      type: 'album',
      uri: 'spotify:album:5Iec810oL6PorbyBVjLnmD'
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/43ZHCT0cAZBISjO8DG9PnE'
        },
        href: 'https://api.spotify.com/v1/artists/43ZHCT0cAZBISjO8DG9PnE',
        id: '43ZHCT0cAZBISjO8DG9PnE',
        name: 'Elvis Presley',
        type: 'artist',
        uri: 'spotify:artist:43ZHCT0cAZBISjO8DG9PnE'
      }
    ],
    available_markets: [
      'AD',
      'AE',
      'AL',
      'AR',
      'AT',
      'AU',
      'BA',
      'BE',
      'BG',
      'BH',
      'BO',
      'BR',
      'BY',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'GT',
      'HK',
      'HN',
      'HR',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IS',
      'IT',
      'JO',
      'JP',
      'KR',
      'KW',
      'KZ',
      'LB',
      'LI',
      'LT',
      'LU',
      'LV',
      'MA',
      'MC',
      'MD',
      'ME',
      'MK',
      'MT',
      'MX',
      'MY',
      'NI',
      'NL',
      'NO',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PH',
      'PL',
      'PS',
      'PT',
      'PY',
      'QA',
      'RO',
      'RS',
      'RU',
      'SA',
      'SE',
      'SG',
      'SI',
      'SK',
      'SV',
      'TH',
      'TN',
      'TR',
      'TW',
      'UA',
      'US',
      'UY',
      'VN',
      'XK',
      'ZA'
    ],
    disc_number: 1,
    duration_ms: 139640,
    explicit: false,
    external_ids: {
      isrc: 'USRC19004482'
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/39zODpVtRvghMyfNjZ3BVK'
    },
    href: 'https://api.spotify.com/v1/tracks/39zODpVtRvghMyfNjZ3BVK',
    id: '39zODpVtRvghMyfNjZ3BVK',
    is_local: false,
    name: 'Stuck on You',
    popularity: 57,
    preview_url: 'https://p.scdn.co/mp3-preview/d1aaf7d0ff8c3096f6745b3c0ff9fe808c949356?cid=774b29d4f13844c495f206cafdad9c86',
    track_number: 2,
    type: 'track',
    uri: 'spotify:track:39zODpVtRvghMyfNjZ3BVK'
  },
  {
    album: {
      album_type: 'ALBUM',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/49e4v89VmlDcFCMyDv9wQ9'
          },
          href: 'https://api.spotify.com/v1/artists/49e4v89VmlDcFCMyDv9wQ9',
          id: '49e4v89VmlDcFCMyDv9wQ9',
          name: 'Dean Martin',
          type: 'artist',
          uri: 'spotify:artist:49e4v89VmlDcFCMyDv9wQ9'
        }
      ],
      available_markets: [
        'AD',
        'AE',
        'AL',
        'AR',
        'AT',
        'AU',
        'BA',
        'BE',
        'BG',
        'BH',
        'BO',
        'BR',
        'BY',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FR',
        'GB',
        'GR',
        'GT',
        'HK',
        'HN',
        'HR',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IS',
        'IT',
        'JO',
        'JP',
        'KR',
        'KW',
        'KZ',
        'LB',
        'LI',
        'LT',
        'LU',
        'LV',
        'MA',
        'MC',
        'MD',
        'ME',
        'MK',
        'MT',
        'MX',
        'MY',
        'NI',
        'NL',
        'NO',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PH',
        'PL',
        'PS',
        'PT',
        'PY',
        'QA',
        'RO',
        'RS',
        'RU',
        'SA',
        'SE',
        'SG',
        'SI',
        'SK',
        'SV',
        'TH',
        'TN',
        'TR',
        'TW',
        'UA',
        'US',
        'UY',
        'VN',
        'XK',
        'ZA'
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/7dfnxOYh1XR9AKqCcGckGX'
      },
      href: 'https://api.spotify.com/v1/albums/7dfnxOYh1XR9AKqCcGckGX',
      id: '7dfnxOYh1XR9AKqCcGckGX',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b2732f13fcfe011d340e9c69923e',
          width: 640
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e022f13fcfe011d340e9c69923e',
          width: 300
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d000048512f13fcfe011d340e9c69923e',
          width: 64
        }
      ],
      name: 'This Is Dean Martin',
      release_date: '1958',
      release_date_precision: 'year',
      total_tracks: 12,
      type: 'album',
      uri: 'spotify:album:7dfnxOYh1XR9AKqCcGckGX'
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/49e4v89VmlDcFCMyDv9wQ9'
        },
        href: 'https://api.spotify.com/v1/artists/49e4v89VmlDcFCMyDv9wQ9',
        id: '49e4v89VmlDcFCMyDv9wQ9',
        name: 'Dean Martin',
        type: 'artist',
        uri: 'spotify:artist:49e4v89VmlDcFCMyDv9wQ9'
      }
    ],
    available_markets: [
      'AD',
      'AE',
      'AL',
      'AR',
      'AT',
      'AU',
      'BA',
      'BE',
      'BG',
      'BH',
      'BO',
      'BR',
      'BY',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'GT',
      'HK',
      'HN',
      'HR',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IS',
      'IT',
      'JO',
      'JP',
      'KR',
      'KW',
      'KZ',
      'LB',
      'LI',
      'LT',
      'LU',
      'LV',
      'MA',
      'MC',
      'MD',
      'ME',
      'MK',
      'MT',
      'MX',
      'MY',
      'NI',
      'NL',
      'NO',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PH',
      'PL',
      'PS',
      'PT',
      'PY',
      'QA',
      'RO',
      'RS',
      'RU',
      'SA',
      'SE',
      'SG',
      'SI',
      'SK',
      'SV',
      'TH',
      'TN',
      'TR',
      'TW',
      'UA',
      'US',
      'UY',
      'VN',
      'XK',
      'ZA'
    ],
    disc_number: 1,
    duration_ms: 181626,
    explicit: false,
    external_ids: {
      isrc: 'USCA29801802'
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/5OkKOkdVTKFrYi6GWXkMzR'
    },
    href: 'https://api.spotify.com/v1/tracks/5OkKOkdVTKFrYi6GWXkMzR',
    id: '5OkKOkdVTKFrYi6GWXkMzR',
    is_local: false,
    name: 'Volare (Nel Blu Di Pinto Di Blu) - Remastered',
    popularity: 64,
    preview_url: null,
    track_number: 1,
    type: 'track',
    uri: 'spotify:track:5OkKOkdVTKFrYi6GWXkMzR'
  },
  {
    album: {
      album_type: 'ALBUM',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/568ZhdwyaiCyOGJRtNYhWf'
          },
          href: 'https://api.spotify.com/v1/artists/568ZhdwyaiCyOGJRtNYhWf',
          id: '568ZhdwyaiCyOGJRtNYhWf',
          name: 'Deep Purple',
          type: 'artist',
          uri: 'spotify:artist:568ZhdwyaiCyOGJRtNYhWf'
        }
      ],
      available_markets: [
        'AD',
        'AE',
        'AL',
        'AR',
        'AT',
        'AU',
        'BA',
        'BE',
        'BG',
        'BH',
        'BO',
        'BR',
        'BY',
        'CH',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FR',
        'GB',
        'GR',
        'GT',
        'HK',
        'HN',
        'HR',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IS',
        'IT',
        'JO',
        'KR',
        'KW',
        'KZ',
        'LB',
        'LI',
        'LT',
        'LU',
        'LV',
        'MA',
        'MC',
        'MD',
        'ME',
        'MK',
        'MT',
        'MX',
        'MY',
        'NI',
        'NL',
        'NO',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PH',
        'PL',
        'PS',
        'PT',
        'PY',
        'QA',
        'RO',
        'RS',
        'RU',
        'SA',
        'SE',
        'SG',
        'SI',
        'SK',
        'SV',
        'TH',
        'TN',
        'TR',
        'TW',
        'UA',
        'UY',
        'VN',
        'XK',
        'ZA'
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/32NQ56VZDTXSH3SMv4XSGN'
      },
      href: 'https://api.spotify.com/v1/albums/32NQ56VZDTXSH3SMv4XSGN',
      id: '32NQ56VZDTXSH3SMv4XSGN',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273a729c9c3dec04b99d889c66f',
          width: 640
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02a729c9c3dec04b99d889c66f',
          width: 300
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851a729c9c3dec04b99d889c66f',
          width: 64
        }
      ],
      name: 'Machine Head (Remastered)',
      release_date: '1972-03-25',
      release_date_precision: 'day',
      total_tracks: 8,
      type: 'album',
      uri: 'spotify:album:32NQ56VZDTXSH3SMv4XSGN'
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/568ZhdwyaiCyOGJRtNYhWf'
        },
        href: 'https://api.spotify.com/v1/artists/568ZhdwyaiCyOGJRtNYhWf',
        id: '568ZhdwyaiCyOGJRtNYhWf',
        name: 'Deep Purple',
        type: 'artist',
        uri: 'spotify:artist:568ZhdwyaiCyOGJRtNYhWf'
      }
    ],
    available_markets: [
      'AD',
      'AE',
      'AL',
      'AR',
      'AT',
      'AU',
      'BA',
      'BE',
      'BG',
      'BH',
      'BO',
      'BR',
      'BY',
      'CH',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'GT',
      'HK',
      'HN',
      'HR',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IS',
      'IT',
      'JO',
      'KR',
      'KW',
      'KZ',
      'LB',
      'LI',
      'LT',
      'LU',
      'LV',
      'MA',
      'MC',
      'MD',
      'ME',
      'MK',
      'MT',
      'MX',
      'MY',
      'NI',
      'NL',
      'NO',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PH',
      'PL',
      'PS',
      'PT',
      'PY',
      'QA',
      'RO',
      'RS',
      'RU',
      'SA',
      'SE',
      'SG',
      'SI',
      'SK',
      'SV',
      'TH',
      'TN',
      'TR',
      'TW',
      'UA',
      'UY',
      'VN',
      'XK',
      'ZA'
    ],
    disc_number: 1,
    duration_ms: 366136,
    explicit: false,
    external_ids: {
      isrc: 'GBDXG1200002'
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/3uMmllZo1AfoEnVT4ENCD3'
    },
    href: 'https://api.spotify.com/v1/tracks/3uMmllZo1AfoEnVT4ENCD3',
    id: '3uMmllZo1AfoEnVT4ENCD3',
    is_local: false,
    name: 'Highway Star - Remastered 2012',
    popularity: 66,
    preview_url: null,
    track_number: 1,
    type: 'track',
    uri: 'spotify:track:3uMmllZo1AfoEnVT4ENCD3'
  },
  {
    album: {
      album_type: 'ALBUM',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/2JSjCHK79gdaiPWdKiNUNp'
          },
          href: 'https://api.spotify.com/v1/artists/2JSjCHK79gdaiPWdKiNUNp',
          id: '2JSjCHK79gdaiPWdKiNUNp',
          name: 'Dionne Warwick',
          type: 'artist',
          uri: 'spotify:artist:2JSjCHK79gdaiPWdKiNUNp'
        }
      ],
      available_markets: [
        'AD',
        'AE',
        'AL',
        'AR',
        'AT',
        'AU',
        'BA',
        'BE',
        'BG',
        'BH',
        'BO',
        'BR',
        'BY',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FR',
        'GB',
        'GR',
        'GT',
        'HK',
        'HN',
        'HR',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IS',
        'IT',
        'JO',
        'JP',
        'KR',
        'KW',
        'KZ',
        'LB',
        'LI',
        'LT',
        'LU',
        'LV',
        'MA',
        'MC',
        'MD',
        'ME',
        'MK',
        'MT',
        'MX',
        'MY',
        'NI',
        'NL',
        'NO',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PH',
        'PL',
        'PS',
        'PT',
        'PY',
        'QA',
        'RO',
        'RS',
        'RU',
        'SA',
        'SE',
        'SG',
        'SI',
        'SK',
        'SV',
        'TH',
        'TN',
        'TR',
        'TW',
        'UA',
        'US',
        'UY',
        'VN',
        'XK',
        'ZA'
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/6edKvdyBPyTPPWCOcTdrhr'
      },
      href: 'https://api.spotify.com/v1/albums/6edKvdyBPyTPPWCOcTdrhr',
      id: '6edKvdyBPyTPPWCOcTdrhr',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b27391f2d96a42e77de7834a8523',
          width: 640
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e0291f2d96a42e77de7834a8523',
          width: 300
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d0000485191f2d96a42e77de7834a8523',
          width: 64
        }
      ],
      name: 'Make Way For Dionne Warwick',
      release_date: '1964',
      release_date_precision: 'year',
      total_tracks: 12,
      type: 'album',
      uri: 'spotify:album:6edKvdyBPyTPPWCOcTdrhr'
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/2JSjCHK79gdaiPWdKiNUNp'
        },
        href: 'https://api.spotify.com/v1/artists/2JSjCHK79gdaiPWdKiNUNp',
        id: '2JSjCHK79gdaiPWdKiNUNp',
        name: 'Dionne Warwick',
        type: 'artist',
        uri: 'spotify:artist:2JSjCHK79gdaiPWdKiNUNp'
      }
    ],
    available_markets: [
      'AD',
      'AE',
      'AL',
      'AR',
      'AT',
      'AU',
      'BA',
      'BE',
      'BG',
      'BH',
      'BO',
      'BR',
      'BY',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'GT',
      'HK',
      'HN',
      'HR',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IS',
      'IT',
      'JO',
      'JP',
      'KR',
      'KW',
      'KZ',
      'LB',
      'LI',
      'LT',
      'LU',
      'LV',
      'MA',
      'MC',
      'MD',
      'ME',
      'MK',
      'MT',
      'MX',
      'MY',
      'NI',
      'NL',
      'NO',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PH',
      'PL',
      'PS',
      'PT',
      'PY',
      'QA',
      'RO',
      'RS',
      'RU',
      'SA',
      'SE',
      'SG',
      'SI',
      'SK',
      'SV',
      'TH',
      'TN',
      'TR',
      'TW',
      'UA',
      'US',
      'UY',
      'VN',
      'XK',
      'ZA'
    ],
    disc_number: 1,
    duration_ms: 178333,
    explicit: false,
    external_ids: {
      isrc: 'USWSP0000173'
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/3xsOtNxtBW0oTI1OWKAzTm'
    },
    href: 'https://api.spotify.com/v1/tracks/3xsOtNxtBW0oTI1OWKAzTm',
    id: '3xsOtNxtBW0oTI1OWKAzTm',
    is_local: false,
    name: 'Walk on By',
    popularity: 60,
    preview_url: 'https://p.scdn.co/mp3-preview/170a73f70575742cd3450a92e37647bfb9159b86?cid=774b29d4f13844c495f206cafdad9c86',
    track_number: 8,
    type: 'track',
    uri: 'spotify:track:3xsOtNxtBW0oTI1OWKAzTm'
  },
  {
    album: {
      album_type: 'ALBUM',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/7K3zpFXBvPcvzhj7zlGJdO'
          },
          href: 'https://api.spotify.com/v1/artists/7K3zpFXBvPcvzhj7zlGJdO',
          id: '7K3zpFXBvPcvzhj7zlGJdO',
          name: 'Crystal Castles',
          type: 'artist',
          uri: 'spotify:artist:7K3zpFXBvPcvzhj7zlGJdO'
        }
      ],
      available_markets: [
        'AD',
        'AE',
        'AR',
        'AT',
        'BA',
        'BE',
        'BG',
        'BH',
        'BO',
        'BR',
        'BY',
        'CH',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DO',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FR',
        'GB',
        'GR',
        'GT',
        'HK',
        'HN',
        'HR',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IS',
        'IT',
        'JO',
        'JP',
        'KR',
        'KW',
        'KZ',
        'LB',
        'LI',
        'LT',
        'LU',
        'LV',
        'MC',
        'MD',
        'ME',
        'MK',
        'MT',
        'MX',
        'MY',
        'NI',
        'NL',
        'NO',
        'OM',
        'PA',
        'PE',
        'PH',
        'PL',
        'PT',
        'PY',
        'QA',
        'RO',
        'RS',
        'RU',
        'SA',
        'SE',
        'SG',
        'SI',
        'SK',
        'SV',
        'TH',
        'TN',
        'TR',
        'TW',
        'UA',
        'US',
        'VN',
        'XK',
        'ZA'
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/37TeO5usN4vsGSfpg4dPNA'
      },
      href: 'https://api.spotify.com/v1/albums/37TeO5usN4vsGSfpg4dPNA',
      id: '37TeO5usN4vsGSfpg4dPNA',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b2735ac6226a668978bf43185e97',
          width: 640
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e025ac6226a668978bf43185e97',
          width: 300
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d000048515ac6226a668978bf43185e97',
          width: 64
        }
      ],
      name: '(II)',
      release_date: '2011-01-01',
      release_date_precision: 'day',
      total_tracks: 14,
      type: 'album',
      uri: 'spotify:album:37TeO5usN4vsGSfpg4dPNA'
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/7K3zpFXBvPcvzhj7zlGJdO'
        },
        href: 'https://api.spotify.com/v1/artists/7K3zpFXBvPcvzhj7zlGJdO',
        id: '7K3zpFXBvPcvzhj7zlGJdO',
        name: 'Crystal Castles',
        type: 'artist',
        uri: 'spotify:artist:7K3zpFXBvPcvzhj7zlGJdO'
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/6G7P2EzH5A36ujN9VPm4B0'
        },
        href: 'https://api.spotify.com/v1/artists/6G7P2EzH5A36ujN9VPm4B0',
        id: '6G7P2EzH5A36ujN9VPm4B0',
        name: 'Robert Smith',
        type: 'artist',
        uri: 'spotify:artist:6G7P2EzH5A36ujN9VPm4B0'
      }
    ],
    available_markets: [
      'AD',
      'AE',
      'AR',
      'AT',
      'BA',
      'BE',
      'BG',
      'BH',
      'BO',
      'BR',
      'BY',
      'CH',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DO',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'GT',
      'HK',
      'HN',
      'HR',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IS',
      'IT',
      'JO',
      'JP',
      'KR',
      'KW',
      'KZ',
      'LB',
      'LI',
      'LT',
      'LU',
      'LV',
      'MC',
      'MD',
      'ME',
      'MK',
      'MT',
      'MX',
      'MY',
      'NI',
      'NL',
      'NO',
      'OM',
      'PA',
      'PE',
      'PH',
      'PL',
      'PT',
      'PY',
      'QA',
      'RO',
      'RS',
      'RU',
      'SA',
      'SE',
      'SG',
      'SI',
      'SK',
      'SV',
      'TH',
      'TN',
      'TR',
      'TW',
      'UA',
      'US',
      'VN',
      'XK',
      'ZA'
    ],
    disc_number: 1,
    duration_ms: 226986,
    explicit: false,
    external_ids: {
      isrc: 'GBUM71029513'
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/46Xnj8vZFwOZCE4aZNXlTf'
    },
    href: 'https://api.spotify.com/v1/tracks/46Xnj8vZFwOZCE4aZNXlTf',
    id: '46Xnj8vZFwOZCE4aZNXlTf',
    is_local: false,
    name: 'Not In Love - Radio Version',
    popularity: 59,
    preview_url: null,
    track_number: 12,
    type: 'track',
    uri: 'spotify:track:46Xnj8vZFwOZCE4aZNXlTf'
  },
  {
    album: {
      album_type: 'ALBUM',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/0p5axeJsbtTCXBrRVoKjwu'
          },
          href: 'https://api.spotify.com/v1/artists/0p5axeJsbtTCXBrRVoKjwu',
          id: '0p5axeJsbtTCXBrRVoKjwu',
          name: 'The Drums',
          type: 'artist',
          uri: 'spotify:artist:0p5axeJsbtTCXBrRVoKjwu'
        }
      ],
      available_markets: [
        'AE',
        'AR',
        'AT',
        'AU',
        'BA',
        'BE',
        'BG',
        'BO',
        'BR',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CZ',
        'DE',
        'DK',
        'DO',
        'EC',
        'EE',
        'ES',
        'FI',
        'FR',
        'GR',
        'GT',
        'HK',
        'HN',
        'HR',
        'HU',
        'IE',
        'IL',
        'IN',
        'IS',
        'IT',
        'JO',
        'KR',
        'KW',
        'LB',
        'LT',
        'LU',
        'LV',
        'ME',
        'MK',
        'MX',
        'MY',
        'NI',
        'NL',
        'NO',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PH',
        'PL',
        'PT',
        'PY',
        'QA',
        'RO',
        'RS',
        'RU',
        'SA',
        'SE',
        'SG',
        'SI',
        'SK',
        'SV',
        'TH',
        'TN',
        'TR',
        'TW',
        'UA',
        'XK',
        'ZA'
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/6n7e5M7KvFflDBmhcl8qMl'
      },
      href: 'https://api.spotify.com/v1/albums/6n7e5M7KvFflDBmhcl8qMl',
      id: '6n7e5M7KvFflDBmhcl8qMl',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b2737864d701a6182a964d495d52',
          width: 640
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e027864d701a6182a964d495d52',
          width: 300
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d000048517864d701a6182a964d495d52',
          width: 64
        }
      ],
      name: 'The Drums',
      release_date: '2010-01-01',
      release_date_precision: 'day',
      total_tracks: 12,
      type: 'album',
      uri: 'spotify:album:6n7e5M7KvFflDBmhcl8qMl'
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/0p5axeJsbtTCXBrRVoKjwu'
        },
        href: 'https://api.spotify.com/v1/artists/0p5axeJsbtTCXBrRVoKjwu',
        id: '0p5axeJsbtTCXBrRVoKjwu',
        name: 'The Drums',
        type: 'artist',
        uri: 'spotify:artist:0p5axeJsbtTCXBrRVoKjwu'
      }
    ],
    available_markets: [
      'AE',
      'AR',
      'AT',
      'AU',
      'BA',
      'BE',
      'BG',
      'BO',
      'BR',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CZ',
      'DE',
      'DK',
      'DO',
      'EC',
      'EE',
      'ES',
      'FI',
      'FR',
      'GR',
      'GT',
      'HK',
      'HN',
      'HR',
      'HU',
      'IE',
      'IL',
      'IN',
      'IS',
      'IT',
      'JO',
      'KR',
      'KW',
      'LB',
      'LT',
      'LU',
      'LV',
      'ME',
      'MK',
      'MX',
      'MY',
      'NI',
      'NL',
      'NO',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PH',
      'PL',
      'PT',
      'PY',
      'QA',
      'RO',
      'RS',
      'RU',
      'SA',
      'SE',
      'SG',
      'SI',
      'SK',
      'SV',
      'TH',
      'TN',
      'TR',
      'TW',
      'UA',
      'XK',
      'ZA'
    ],
    disc_number: 1,
    duration_ms: 174306,
    explicit: false,
    external_ids: {
      isrc: 'GBGEY0900107'
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/6NtLv8Gib08OxCYWZ8xc3i'
    },
    href: 'https://api.spotify.com/v1/tracks/6NtLv8Gib08OxCYWZ8xc3i',
    id: '6NtLv8Gib08OxCYWZ8xc3i',
    is_local: false,
    name: 'Lets Go Surfing',
    popularity: 57,
    preview_url: null,
    track_number: 3,
    type: 'track',
    uri: 'spotify:track:6NtLv8Gib08OxCYWZ8xc3i'
  },
  {
    album: {
      album_type: 'ALBUM',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/1dfeR4HaWDbWqFHLkxsg1d'
          },
          href: 'https://api.spotify.com/v1/artists/1dfeR4HaWDbWqFHLkxsg1d',
          id: '1dfeR4HaWDbWqFHLkxsg1d',
          name: 'Queen',
          type: 'artist',
          uri: 'spotify:artist:1dfeR4HaWDbWqFHLkxsg1d'
        }
      ],
      available_markets: [
        'AD',
        'AE',
        'AL',
        'AR',
        'AT',
        'AU',
        'BA',
        'BE',
        'BG',
        'BH',
        'BO',
        'BR',
        'BY',
        'CH',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FR',
        'GB',
        'GR',
        'GT',
        'HK',
        'HN',
        'HR',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IS',
        'IT',
        'JO',
        'JP',
        'KR',
        'KW',
        'KZ',
        'LB',
        'LI',
        'LT',
        'LU',
        'LV',
        'MA',
        'MC',
        'MD',
        'ME',
        'MK',
        'MT',
        'MX',
        'MY',
        'NI',
        'NL',
        'NO',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PH',
        'PL',
        'PS',
        'PT',
        'PY',
        'QA',
        'RO',
        'RS',
        'RU',
        'SA',
        'SE',
        'SG',
        'SI',
        'SK',
        'SV',
        'TH',
        'TN',
        'TR',
        'TW',
        'UA',
        'UY',
        'VN',
        'XK',
        'ZA'
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/75eP8LZolyNBpqIRyB5pvB'
      },
      href: 'https://api.spotify.com/v1/albums/75eP8LZolyNBpqIRyB5pvB',
      id: '75eP8LZolyNBpqIRyB5pvB',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273733cfd7114c704785e4f8da0',
          width: 640
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02733cfd7114c704785e4f8da0',
          width: 300
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851733cfd7114c704785e4f8da0',
          width: 64
        }
      ],
      name: 'A Night At The Opera (Deluxe Edition 2011 Remaster)',
      release_date: '1975-11-21',
      release_date_precision: 'day',
      total_tracks: 18,
      type: 'album',
      uri: 'spotify:album:75eP8LZolyNBpqIRyB5pvB'
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/1dfeR4HaWDbWqFHLkxsg1d'
        },
        href: 'https://api.spotify.com/v1/artists/1dfeR4HaWDbWqFHLkxsg1d',
        id: '1dfeR4HaWDbWqFHLkxsg1d',
        name: 'Queen',
        type: 'artist',
        uri: 'spotify:artist:1dfeR4HaWDbWqFHLkxsg1d'
      }
    ],
    available_markets: [
      'AD',
      'AE',
      'AL',
      'AR',
      'AT',
      'AU',
      'BA',
      'BE',
      'BG',
      'BH',
      'BO',
      'BR',
      'BY',
      'CH',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'GT',
      'HK',
      'HN',
      'HR',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IS',
      'IT',
      'JO',
      'JP',
      'KR',
      'KW',
      'KZ',
      'LB',
      'LI',
      'LT',
      'LU',
      'LV',
      'MA',
      'MC',
      'MD',
      'ME',
      'MK',
      'MT',
      'MX',
      'MY',
      'NI',
      'NL',
      'NO',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PH',
      'PL',
      'PS',
      'PT',
      'PY',
      'QA',
      'RO',
      'RS',
      'RU',
      'SA',
      'SE',
      'SG',
      'SI',
      'SK',
      'SV',
      'TH',
      'TN',
      'TR',
      'TW',
      'UA',
      'UY',
      'VN',
      'XK',
      'ZA'
    ],
    disc_number: 1,
    duration_ms: 210800,
    explicit: false,
    external_ids: {
      isrc: 'GBUM71100531'
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/65NTcXUtOb27NHKQ4fAcw0'
    },
    href: 'https://api.spotify.com/v1/tracks/65NTcXUtOb27NHKQ4fAcw0',
    id: '65NTcXUtOb27NHKQ4fAcw0',
    is_local: false,
    name: "'39 - Remastered 2011",
    popularity: 56,
    preview_url: null,
    track_number: 5,
    type: 'track',
    uri: 'spotify:track:65NTcXUtOb27NHKQ4fAcw0'
  },
  {
    album: {
      album_type: 'ALBUM',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/3HJIB8sYPyxrFGuwvKXSLR'
          },
          href: 'https://api.spotify.com/v1/artists/3HJIB8sYPyxrFGuwvKXSLR',
          id: '3HJIB8sYPyxrFGuwvKXSLR',
          name: 'TV On The Radio',
          type: 'artist',
          uri: 'spotify:artist:3HJIB8sYPyxrFGuwvKXSLR'
        }
      ],
      available_markets: [
        'CA',
        'US'
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/3bWZ33ZCvHQD3nJnPjpfk7'
      },
      href: 'https://api.spotify.com/v1/albums/3bWZ33ZCvHQD3nJnPjpfk7',
      id: '3bWZ33ZCvHQD3nJnPjpfk7',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273fdb73543b5bec0aa2275f846',
          width: 640
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02fdb73543b5bec0aa2275f846',
          width: 300
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851fdb73543b5bec0aa2275f846',
          width: 64
        }
      ],
      name: 'Dear Science',
      release_date: '2008-01-01',
      release_date_precision: 'day',
      total_tracks: 15,
      type: 'album',
      uri: 'spotify:album:3bWZ33ZCvHQD3nJnPjpfk7'
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/3HJIB8sYPyxrFGuwvKXSLR'
        },
        href: 'https://api.spotify.com/v1/artists/3HJIB8sYPyxrFGuwvKXSLR',
        id: '3HJIB8sYPyxrFGuwvKXSLR',
        name: 'TV On The Radio',
        type: 'artist',
        uri: 'spotify:artist:3HJIB8sYPyxrFGuwvKXSLR'
      }
    ],
    available_markets: [
      'CA',
      'US'
    ],
    disc_number: 1,
    duration_ms: 228706,
    explicit: false,
    external_ids: {
      isrc: 'USTG30828010'
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/3GQmoKZvsd2P3G5OJLAZCp'
    },
    href: 'https://api.spotify.com/v1/tracks/3GQmoKZvsd2P3G5OJLAZCp',
    id: '3GQmoKZvsd2P3G5OJLAZCp',
    is_local: false,
    name: 'DLZ',
    popularity: 47,
    preview_url: null,
    track_number: 10,
    type: 'track',
    uri: 'spotify:track:3GQmoKZvsd2P3G5OJLAZCp'
  },
  {
    album: {
      album_type: 'ALBUM',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/6xrCU6zdcSTsG2hLrojpmI'
          },
          href: 'https://api.spotify.com/v1/artists/6xrCU6zdcSTsG2hLrojpmI',
          id: '6xrCU6zdcSTsG2hLrojpmI',
          name: 'José González',
          type: 'artist',
          uri: 'spotify:artist:6xrCU6zdcSTsG2hLrojpmI'
        }
      ],
      available_markets: [
        'CA',
        'US'
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/2e0BYdQ7VJlzSNHafdmfrl'
      },
      href: 'https://api.spotify.com/v1/albums/2e0BYdQ7VJlzSNHafdmfrl',
      id: '2e0BYdQ7VJlzSNHafdmfrl',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b2731017779b8f5fe0ccd77bf886',
          width: 640
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e021017779b8f5fe0ccd77bf886',
          width: 300
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d000048511017779b8f5fe0ccd77bf886',
          width: 64
        }
      ],
      name: 'Veneer',
      release_date: '2006',
      release_date_precision: 'year',
      total_tracks: 11,
      type: 'album',
      uri: 'spotify:album:2e0BYdQ7VJlzSNHafdmfrl'
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/6xrCU6zdcSTsG2hLrojpmI'
        },
        href: 'https://api.spotify.com/v1/artists/6xrCU6zdcSTsG2hLrojpmI',
        id: '6xrCU6zdcSTsG2hLrojpmI',
        name: 'José González',
        type: 'artist',
        uri: 'spotify:artist:6xrCU6zdcSTsG2hLrojpmI'
      }
    ],
    available_markets: [
      'CA',
      'US'
    ],
    disc_number: 1,
    duration_ms: 162920,
    explicit: false,
    external_ids: {
      isrc: 'SEVVX0300101'
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/0ByKWq0hsuYriK5avSMJ5r'
    },
    href: 'https://api.spotify.com/v1/tracks/0ByKWq0hsuYriK5avSMJ5r',
    id: '0ByKWq0hsuYriK5avSMJ5r',
    is_local: false,
    name: 'Crosses',
    popularity: 50,
    preview_url: 'https://p.scdn.co/mp3-preview/6101041416a128e2e3b9372f312ff505a5aa67a9?cid=774b29d4f13844c495f206cafdad9c86',
    track_number: 5,
    type: 'track',
    uri: 'spotify:track:0ByKWq0hsuYriK5avSMJ5r'
  },
  {
    album: {
      album_type: 'ALBUM',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/762310PdDnwsDxAQxzQkfX'
          },
          href: 'https://api.spotify.com/v1/artists/762310PdDnwsDxAQxzQkfX',
          id: '762310PdDnwsDxAQxzQkfX',
          name: 'Depeche Mode',
          type: 'artist',
          uri: 'spotify:artist:762310PdDnwsDxAQxzQkfX'
        }
      ],
      available_markets: [
        'AD',
        'AE',
        'AL',
        'AR',
        'AT',
        'AU',
        'BA',
        'BE',
        'BG',
        'BH',
        'BO',
        'BR',
        'BY',
        'CH',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FR',
        'GB',
        'GR',
        'GT',
        'HK',
        'HN',
        'HR',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IS',
        'IT',
        'JO',
        'JP',
        'KR',
        'KW',
        'KZ',
        'LB',
        'LI',
        'LT',
        'LU',
        'LV',
        'MA',
        'MC',
        'MD',
        'ME',
        'MK',
        'MT',
        'MY',
        'NI',
        'NL',
        'NO',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PH',
        'PL',
        'PS',
        'PT',
        'PY',
        'QA',
        'RO',
        'RS',
        'RU',
        'SA',
        'SE',
        'SG',
        'SI',
        'SK',
        'SV',
        'TH',
        'TN',
        'TR',
        'TW',
        'UA',
        'UY',
        'VN',
        'XK',
        'ZA'
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/0Zp2eVzR9FW6lKX05lRpcu'
      },
      href: 'https://api.spotify.com/v1/albums/0Zp2eVzR9FW6lKX05lRpcu',
      id: '0Zp2eVzR9FW6lKX05lRpcu',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b27388ffe8c41647856e6fa5e1ab',
          width: 640
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e0288ffe8c41647856e6fa5e1ab',
          width: 300
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d0000485188ffe8c41647856e6fa5e1ab',
          width: 64
        }
      ],
      name: 'Speak And Spell (Deluxe)',
      release_date: '1981-11-02',
      release_date_precision: 'day',
      total_tracks: 16,
      type: 'album',
      uri: 'spotify:album:0Zp2eVzR9FW6lKX05lRpcu'
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/762310PdDnwsDxAQxzQkfX'
        },
        href: 'https://api.spotify.com/v1/artists/762310PdDnwsDxAQxzQkfX',
        id: '762310PdDnwsDxAQxzQkfX',
        name: 'Depeche Mode',
        type: 'artist',
        uri: 'spotify:artist:762310PdDnwsDxAQxzQkfX'
      }
    ],
    available_markets: [
      'AD',
      'AE',
      'AL',
      'AR',
      'AT',
      'AU',
      'BA',
      'BE',
      'BG',
      'BH',
      'BO',
      'BR',
      'BY',
      'CH',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'GT',
      'HK',
      'HN',
      'HR',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IS',
      'IT',
      'JO',
      'JP',
      'KR',
      'KW',
      'KZ',
      'LB',
      'LI',
      'LT',
      'LU',
      'LV',
      'MA',
      'MC',
      'MD',
      'ME',
      'MK',
      'MT',
      'MY',
      'NI',
      'NL',
      'NO',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PH',
      'PL',
      'PS',
      'PT',
      'PY',
      'QA',
      'RO',
      'RS',
      'RU',
      'SA',
      'SE',
      'SG',
      'SI',
      'SK',
      'SV',
      'TH',
      'TN',
      'TR',
      'TW',
      'UA',
      'UY',
      'VN',
      'XK',
      'ZA'
    ],
    disc_number: 1,
    duration_ms: 220893,
    explicit: false,
    external_ids: {
      isrc: 'GBAJH0600205'
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/0qi4b1l0eT3jpzeNHeFXDT'
    },
    href: 'https://api.spotify.com/v1/tracks/0qi4b1l0eT3jpzeNHeFXDT',
    id: '0qi4b1l0eT3jpzeNHeFXDT',
    is_local: false,
    name: "Just Can't Get Enough",
    popularity: 69,
    preview_url: 'https://p.scdn.co/mp3-preview/899caa29746e4ea35731fcf93a307821b1583c2b?cid=774b29d4f13844c495f206cafdad9c86',
    track_number: 11,
    type: 'track',
    uri: 'spotify:track:0qi4b1l0eT3jpzeNHeFXDT'
  }
];
jest.mock('../../flux/stores/stores');

describe('Given the Recommendations component', () => {
  let container;
  beforeEach(() => {
    container = document.createElement('div');
    document.body.appendChild(container);
  });

  afterEach(() => {
    unmountComponentAtNode(container);
    container.remove();
  });

  describe('when the component is rendered', () => {
    test('A section is created with the appropiate className attribute', () => {
      spotifindStore.getRecommendationsSeed.mockImplementation(() => mockData);
      act(() => {
        // eslint-disable-next-line react/jsx-filename-extension
        render(<BrowserRouter>
          <RecommendationsSeeds />
        </BrowserRouter>, container);
      });
      const sectionClass = document.querySelector('section').className;

      expect(sectionClass).toBe('dashboard__recommendations');
    });
  });
});
