export default {

  LOAD_DASHBOARD: 'LOAD_DASHBOARD',
  LOAD_USER_PROFILE: 'LOAD_USER_PROFILE',
  LOAD_PRODUCT_STATS: 'LOAD_PRODUCT_STATS',
  REGISTER: 'REGISTER',
  LOG_IN: 'LOG_IN',
  LOG_OUT: 'LOG_OUT',
  FEEDBACK_NEW: 'FEEDBACK_NEW',
  FEEDBACK_BROKEN: 'FEEDBACK_BROKEN',
  SEARCH_PRODUCT: 'SEARCH_PRODUCT',
  VALIDATE_DEATH_REASON: 'VALIDATE_DEATH_REASON'

};
